using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using Touchline.Core;
namespace Touchline.Editor
{
 public static class GoalBallVisibilityReview
 {
  [Serializable] class Clip{public string id,statePath,targetPlayer;public float durationSeconds;}
  [Serializable] class Index{public Clip[] clips;}
  [Serializable] class MeshAudit{public string name;public int triangles,outward,inward,degenerate;public float minRadius,maxRadius,minNormalDot,maxNormalDot;public Vector3 bounds;}
  [Serializable] class MaterialAudit{public string shader;public Color color;public int renderQueue;public float cull,surface;}
  [Serializable] class Frame{public int frame;public string phase;public Vector3 ball,inspectionViewport,fieldViewport;public float diameterInspectionPx,diameterFieldPx;public bool rendererEnabled;public string inspectionFile,fieldFile,noNetFile;}
  [Serializable] class Report{public bool passed,physicalAndroid=false;public string limitation="Production saved Core sequence and exact current baked poses. Field-side camera and net-disabled captures are diagnostic only; no production camera/mesh change. Visibility verdict requires image inspection.";public MeshAudit ballMesh,unitySphereMesh;public Vector3 ballScale,ballWorldBounds;public MaterialAudit[] materials;public Frame[] frames;}
  static string Arg(string key,string fallback)=>Environment.GetCommandLineArgs().FirstOrDefault(a=>a.StartsWith(key+"="))?.Substring(key.Length+1)??fallback;
  static MeshAudit Audit(Mesh mesh){var vertices=mesh.vertices;var normals=mesh.normals;var indices=mesh.triangles;var r=new MeshAudit{name=mesh.name,triangles=indices.Length/3,minRadius=float.MaxValue,minNormalDot=1,maxNormalDot=-1,bounds=mesh.bounds.size};for(int i=0;i<vertices.Length;i++){r.minRadius=Mathf.Min(r.minRadius,vertices[i].magnitude);r.maxRadius=Mathf.Max(r.maxRadius,vertices[i].magnitude);if(i<normals.Length){float d=Vector3.Dot(vertices[i].normalized,normals[i].normalized);r.minNormalDot=Mathf.Min(r.minNormalDot,d);r.maxNormalDot=Mathf.Max(r.maxNormalDot,d);}}for(int i=0;i<indices.Length;i+=3){var a=vertices[indices[i]];var b=vertices[indices[i+1]];var c=vertices[indices[i+2]];float d=Vector3.Dot(Vector3.Cross(b-a,c-a),(a+b+c)/3);if(d>1e-9f)r.outward++;else if(d< -1e-9f)r.inward++;else r.degenerate++;}return r;}
  static void Capture(Camera camera,RenderTexture target,GameObject root,string path){var skins=new List<SkinnedMeshRenderer>();var proxies=new List<GameObject>();var meshes=new List<Mesh>();var previous=RenderTexture.active;Texture2D image=null;try{foreach(var skin in root.GetComponentsInChildren<SkinnedMeshRenderer>()){if(!skin.enabled||!skin.gameObject.activeInHierarchy)continue;var mesh=new Mesh();skin.BakeMesh(mesh);meshes.Add(mesh);var proxy=new GameObject("Exact current skin");proxy.layer=skin.gameObject.layer;proxy.transform.SetParent(skin.transform,false);proxy.AddComponent<MeshFilter>().sharedMesh=mesh;proxy.AddComponent<MeshRenderer>().sharedMaterials=skin.sharedMaterials;proxies.Add(proxy);skins.Add(skin);skin.enabled=false;}camera.Render();RenderTexture.active=target;image=new Texture2D(target.width,target.height,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,target.width,target.height),0,0);image.Apply();File.WriteAllBytes(path,image.EncodeToPNG());}finally{foreach(var skin in skins)skin.enabled=true;foreach(var proxy in proxies)UnityEngine.Object.DestroyImmediate(proxy);foreach(var mesh in meshes)UnityEngine.Object.DestroyImmediate(mesh);if(image!=null)UnityEngine.Object.DestroyImmediate(image);RenderTexture.active=previous;}}
  static Camera CameraAt(string name,RenderTexture target){var c=new GameObject(name).AddComponent<Camera>();c.enabled=false;c.fieldOfView=43;c.nearClipPlane=.15f;c.farClipPlane=270;c.clearFlags=CameraClearFlags.SolidColor;c.backgroundColor=RenderSettings.fogColor;c.aspect=1.5f;c.targetTexture=target;return c;}
  static float Diameter(Camera camera,Vector3 p)=>.22f*640/(2*Mathf.Tan(camera.fieldOfView*Mathf.Deg2Rad*.5f)*camera.WorldToViewportPoint(p).z);
  public static void Run(){try{
   string name=Arg("-touchlineGoalBallVisibilityOutput","goal-ball-visibility-v1"),pack=Arg("-touchlineNaturalPack","natural-match-sequences-20261005-v4");if(!System.Text.RegularExpressions.Regex.IsMatch(name,"^[a-zA-Z0-9-]+$")||!System.Text.RegularExpressions.Regex.IsMatch(pack,"^[a-zA-Z0-9-]+$"))throw new Exception("Invalid proof path");
   string input=Path.GetFullPath("../../artifacts/research/"+pack),output=Path.GetFullPath("../../artifacts/unity/"+name);if(Directory.Exists(output))throw new Exception("Preserve previous proof");Directory.CreateDirectory(output);
   var clip=JsonUtility.FromJson<Index>(File.ReadAllText(Path.Combine(input,"index.json"))).clips.Single(c=>c.id=="06-goal");var db=JsonUtility.FromJson<Database>(File.ReadAllText(Path.Combine(input,"database.json")));var state=JsonUtility.FromJson<MatchState>(File.ReadAllText(Path.Combine(input,clip.statePath)));EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);var root=new GameObject("Goal ball native visibility audit");var arena=root.AddComponent<MatchArena>();arena.Initialize(db,new MatchSimulation(db,state));arena.Speed=1;arena.Paused=false;arena.Broadcast.SetMode(MatchViewingMode.Full);
   var ball=root.GetComponentsInChildren<MeshFilter>().Single(f=>f.sharedMesh==FootballBallMesh.Shared);var renderer=ball.GetComponent<MeshRenderer>();var sphere=GameObject.CreatePrimitive(PrimitiveType.Sphere);var sphereAudit=Audit(sphere.GetComponent<MeshFilter>().sharedMesh);UnityEngine.Object.DestroyImmediate(sphere);
   var materials=renderer.sharedMaterials.Select(m=>new MaterialAudit{shader=m.shader.name,color=m.HasProperty("_BaseColor")?m.GetColor("_BaseColor"):m.color,renderQueue=m.renderQueue,cull=m.HasProperty("_Cull")?m.GetFloat("_Cull"):-1,surface=m.HasProperty("_Surface")?m.GetFloat("_Surface"):-1}).ToArray();var meshAudit=Audit(ball.sharedMesh);var target=new RenderTexture(960,640,24){antiAliasing=2};target.Create();var inspection=CameraAt("Original inspection tracking",target);var field=CameraAt("Field-side visibility diagnosis",target);arena.MatchCamera.targetTexture=target;arena.MatchCamera.aspect=1.5f;
   int ai=Array.FindIndex(state.actors,a=>a.id==clip.targetPlayer);var selected=new HashSet<int>(new[]{58,60,61,62,65,70,75,90});var frames=new List<Frame>();Vector3 focus=Vector3.zero,velocity=Vector3.zero;var nets=root.GetComponentsInChildren<MeshFilter>().Where(f=>f.sharedMesh!=null&&f.sharedMesh.name=="Woven goal net").Select(f=>f.GetComponent<MeshRenderer>()).ToArray();
   for(int i=0;i<=90;i++){
    arena.RenderFrame(1f/30);var position=arena.BallDisplayPosition;var desired=Vector3.Lerp(arena.PlayerVisual(ai).transform.position,position,.3f);desired.y=1;if(i==0)focus=desired;else focus=Vector3.SmoothDamp(focus,desired,ref velocity,.22f,50,1f/30);inspection.transform.position=focus+new Vector3(9,5.7f,9);inspection.transform.LookAt(focus);
    float side=position.x>=0?1:-1;field.transform.position=new Vector3(side*44,3.8f,0);field.transform.LookAt(new Vector3(side*53.4f,1.2f,0));
    if(!selected.Contains(i))continue;string a="inspection-"+i.ToString("D3")+".png",b="field-"+i.ToString("D3")+".png",c="field-no-net-"+i.ToString("D3")+".png";Capture(inspection,target,root,Path.Combine(output,a));Capture(field,target,root,Path.Combine(output,b));foreach(var net in nets)net.enabled=false;try{Capture(field,target,root,Path.Combine(output,c));}finally{foreach(var net in nets)net.enabled=true;}
    frames.Add(new Frame{frame=i,phase=state.phase,ball=position,inspectionViewport=inspection.WorldToViewportPoint(position),fieldViewport=field.WorldToViewportPoint(position),diameterInspectionPx=Diameter(inspection,position),diameterFieldPx=Diameter(field,position),rendererEnabled=renderer.enabled,inspectionFile=a,fieldFile=b,noNetFile=c});
   }
   var report=new Report{passed=frames.Count==selected.Count&&frames.Any(f=>f.phase=="goal"),ballMesh=meshAudit,unitySphereMesh=sphereAudit,ballScale=ball.transform.lossyScale,ballWorldBounds=renderer.bounds.size,materials=materials,frames=frames.ToArray()};File.WriteAllText(Path.Combine(output,"report.json"),JsonUtility.ToJson(report,true));if(!report.passed)throw new Exception("Missing expected natural goal frames");Debug.Log("TOUCHLINE_GOAL_BALL_VISIBILITY_OK");EditorApplication.Exit(0);
  }catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 }
}
