using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Touchline.Core;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace Touchline.Editor
{
    [InitializeOnLoad] public static class LaunchMenuSmoke
    {
        static int stage,frames,last=-1;static RenderTexture target;static string primary,initialPrimary,initialBackup,output;static float heldClock;static int size,motion;
        static string ReportDirectory{get{const string prefix="-touchlineLaunchOutput=";var requested=Environment.GetCommandLineArgs().FirstOrDefault(a=>a.StartsWith(prefix,StringComparison.Ordinal));var name=requested==null?"launch-menu-034":requested.Substring(prefix.Length);if(name.Length==0||!name.All(c=>char.IsLetterOrDigit(c)||c=='-'))throw new ArgumentException("Invalid launch capture folder");return Path.GetFullPath("../../artifacts/unity/"+name);}}
        const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
        static LaunchMenuSmoke(){EditorApplication.update+=Tick;}
        public static void Run(){ProjectBuilder.Configure();output=ReportDirectory;Directory.CreateDirectory(output);string scratch=Path.Combine(output,"scratch-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(scratch);SessionState.SetString("TouchlineLaunchSaveRoot",scratch);primary=Path.Combine(scratch,"touchline-unity-career.json");var db=JsonUtility.FromJson<Database>(AssetDatabase.LoadAssetAtPath<TextAsset>("Assets/Touchline/Resources/Data/database.json").text);var c=new Career{manager="Menu Validation",club="176"};c.lineup=Career.Select(db,c.club,c.tactic);c.EnsureLife(db);c.life.day=10;File.WriteAllText(primary,JsonUtility.ToJson(c));c.life.day=5;File.WriteAllText(primary+".backup",JsonUtility.ToJson(c));size=PlayerPrefs.GetInt("interface-size",1);motion=PlayerPrefs.GetInt("reduce-motion",0);SessionState.SetInt("LaunchOriginalSize",size);SessionState.SetInt("LaunchOriginalMotion",motion);SessionState.SetBool("TouchlineLaunchSmoke",true);EditorApplication.isPlaying=true;}
        static TouchlineApp App=>TouchlineApp.Instance;
        static VisualElement Root=>App.GetComponent<UIDocument>().rootVisualElement;
        static object Call(string name,params object[] args)=>typeof(TouchlineApp).GetMethod(name,Private).Invoke(App,args);
        static void Field(string name,object value)=>typeof(TouchlineApp).GetField(name,Private).SetValue(App,value);
        static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
        static void Click(string name){var b=Root.Query<Button>().ToList().FirstOrDefault(x=>x.name==name||x.text==name);Check(b!=null,"Missing "+name);using(var e=NavigationSubmitEvent.GetPooled()){e.target=b;b.SendEvent(e);}}
        static void Resize(int w,int h){var old=target;target=new RenderTexture(w,h,24);target.Create();App.GetComponent<UIDocument>().panelSettings.targetTexture=target;if(old!=null){old.Release();UnityEngine.Object.DestroyImmediate(old);}}
        static void Capture(string file){var old=RenderTexture.active;RenderTexture.active=target;var image=new Texture2D(target.width,target.height,TextureFormat.RGBA32,false);image.ReadPixels(new Rect(0,0,target.width,target.height),0,0);image.Apply();File.WriteAllBytes(Path.Combine(output,file),image.EncodeToPNG());UnityEngine.Object.DestroyImmediate(image);RenderTexture.active=old;}
        static void NoWrites(){Check(File.ReadAllText(primary)==initialPrimary&&File.ReadAllText(primary+".backup")==initialBackup,"Menu browsing modified a career file");}
        static void HomeVisible(){var viewport=Root.Q<ScrollView>(className:"launch-home-scroll").contentViewport.worldBound;foreach(var name in new[]{"launch-resume","launch-new","launch-saves","launch-settings"}){var b=Root.Q<Button>(name);Check(b!=null&&b.worldBound.yMin>=viewport.yMin-1&&b.worldBound.yMax<=viewport.yMax+1,"Primary launch command requires scrolling in landscape: "+name+" button="+b?.worldBound+" viewport="+viewport+" root="+Root.worldBound);}}
        static void Bounds(){foreach(var b in Root.Query<Button>(className:"launch-action").ToList().Concat(new[]{Root.Q<Button>("launch-resume")}).Where(b=>b!=null)){Check(b.worldBound.width>=44&&b.worldBound.height>=44,"Small launch target: "+b.name);Check(b.worldBound.xMin>=Root.worldBound.xMin-1&&b.worldBound.xMax<=Root.worldBound.xMax+1,"Launch target exceeds viewport: "+b.name);}}
        static void Tick(){if(!SessionState.GetBool("TouchlineLaunchSmoke",false)||!EditorApplication.isPlaying||App==null)return;if(last==Time.frameCount)return;last=Time.frameCount;if(++frames<16)return;frames=0;
            try{output=ReportDirectory;primary=Path.Combine(SessionState.GetString("TouchlineLaunchSaveRoot",""),"touchline-unity-career.json");switch(stage++){
                case 0:initialPrimary=File.ReadAllText(primary);initialBackup=File.ReadAllText(primary+".backup");Check(App.LaunchMenuVisible&&!App.HasSelectedCareer&&App.SaveRequestCount==0,"Startup created or adopted a career automatically");Resize(1600,700);break;
                case 1:Capture("launch-fit-diagnostic.png");Bounds();HomeVisible();NoWrites();Click("launch-quit");Check(Root.Q("launch-quit-confirmation")!=null,"Quit lacks confirmation");Click("launch-quit-cancel");NoWrites();Capture("launch-landscape.png");Click("launch-settings");break;
                case 2:Check(Root.Q("launch-menu")!=null&&!App.HasSelectedCareer,"Settings require an active career");Root.Query<DropdownField>().ToList().First(f=>f.label=="Taille de l’interface").index=2;Capture("launch-settings.png");Click("launch-back");Click("launch-new");Root.Q<TextField>("launch-manager-name").value="Victor Validation";Root.Q<Toggle>("launch-reveal-attributes").value=true;Root.Q<TextField>("launch-club-search").value="Marseille";Click("launch-club-176");Resize(1080,2520);break;
                case 3:Check(Root.Q<TextField>("launch-manager-name").value=="Victor Validation"&&Root.Q<Toggle>("launch-reveal-attributes").value,"Rotation discarded the unsent career draft");Check(Root.Q<Label>("launch-reveal-description").text.StartsWith("Attributs visibles"),"Attribute disclosure explanation contradicts the selected mode");NoWrites();Capture("launch-new-portrait.png");Root.Q<Toggle>("launch-reveal-attributes").value=false;Check(Root.Q<Label>("launch-reveal-description").text.StartsWith("Observation nécessaire"),"Hidden mode explanation missing");Root.Q<Toggle>("launch-reveal-attributes").value=true;Click("launch-create-career");break;
                case 4:Check(Root.Q("launch-new-confirmation")!=null,"New career requires a concrete confirmation");NoWrites();Capture("launch-confirmation.png");Click("launch-new-cancel");Click("launch-back");Click("launch-saves");break;
                case 5:NoWrites();Capture("launch-saves.png");Click("launch-load-backup");break;
                case 6:Check(App.HasSelectedCareer&&!App.LaunchMenuVisible&&App.Career.life.day==5&&!App.Career.revealAttributes,"Backup restore or draft isolation failed");NoWrites();App.Save();Check(File.Exists(primary)&&LaunchCareerStorage.Read(primary,"Principal",App.Database).Valid,"Explicit save did not create a valid primary");var opponent=App.Database.clubs.First(c=>c.playable&&c.league==App.Database.clubs.First(x=>x.id==App.Career.club).league&&c.id!=App.Career.club).id;App.Career.match=MatchSimulation.Create(App.Database,App.Career,opponent,73,2700).State;Call("Navigate","Match");break;
                case 7:var arena=UnityEngine.Object.FindFirstObjectByType<MatchArena>();arena.Paused=false;break;
                case 8:Call("ClubDirectory");Click("manager-main-menu");heldClock=App.Career.match.clock;Check(App.LaunchMenuVisible,"In-game menu action is missing");break;
                case 9:var paused=UnityEngine.Object.FindFirstObjectByType<MatchArena>(FindObjectsInactive.Include);Check(paused.Paused&&!paused.gameObject.activeSelf&&App.Career.match.clock==heldClock,"Match continued behind launch menu");Bounds();Capture("launch-match-resume.png");Click("launch-resume");break;
                case 10:Check(!App.LaunchMenuVisible&&UnityEngine.Object.FindFirstObjectByType<MatchArena>().Paused&&App.Career.match.clock==heldClock,"Resuming restarted the clock without user playback");Call("ReturnToLaunchMenu");Field("careerSelected",false);File.WriteAllText(primary,"{broken");File.WriteAllText(primary+".backup",initialBackup);Call("RefreshLaunchSaves");Call("BuildLaunchMenu");initialPrimary="{broken";Call("OnApplicationPause",true);Call("OnApplicationQuit");NoWrites();break;
                case 11:Check(Root.Query<Label>().ToList().Any(l=>l.text.Contains("secours peut être récupéré")),"Recovery is not explained");Capture("launch-recovery.png");Click("launch-resume");break;
                case 12:Check(App.Career.life.day==5&&!App.LaunchMenuVisible,"Readable backup was not recovered");NoWrites();Call("ReturnToLaunchMenu");Check(File.ReadAllText(primary+".backup")==initialBackup&&Directory.GetFiles(Path.GetDirectoryName(primary),"*.invalid-*").Any(f=>File.ReadAllText(f)=="{broken"),"Recovery destroyed the backup or damaged original");Click("launch-new");Root.Q<TextField>("launch-manager-name").value="Victor Nouveau";Click("launch-create-career");Click("launch-new-confirm");break;
                case 13:if(App.LaunchMenuVisible){stage--;return;}Check(App.Career.manager=="Victor Nouveau"&&App.Career.club=="176"&&App.Career.life.day==0&&App.Career.revealAttributes,"Confirmed draft did not become a fresh summer career");Call("ReturnToLaunchMenu");Resize(1600,700);break;
                case 14:Bounds();HomeVisible();Capture("launch-new-resume.png");PlayerPrefs.SetInt("interface-size",SessionState.GetInt("LaunchOriginalSize",1));PlayerPrefs.SetInt("reduce-motion",SessionState.GetInt("LaunchOriginalMotion",0));PlayerPrefs.Save();File.WriteAllText(Path.Combine(output,"report.json"),"{\"passed\":true,\"stages\":15,\"nativeLaunch\":true,\"noMenuCareerWrites\":true,\"readableBackupRecovery\":true,\"corruptOriginalPreserved\":true,\"newCareerConfirmation\":true,\"draftSurvivesRotation\":true,\"matchPausedAndHidden\":true,\"resumeDoesNotAutoPlay\":true,\"settingsWithoutCareer\":true,\"portraitAndLandscape\":true,\"landscapeCommandsVisibleWithoutScroll\":true,\"realWorldGenerationSkippedForVisualValidation\":true,\"personalSaveWrites\":false,\"physicalAndroid\":false}");SessionState.SetBool("TouchlineLaunchSmoke",false);Debug.Log("TOUCHLINE_LAUNCH_MENU_OK");EditorApplication.Exit(0);break;
            }}catch(Exception error){PlayerPrefs.SetInt("interface-size",SessionState.GetInt("LaunchOriginalSize",1));PlayerPrefs.SetInt("reduce-motion",SessionState.GetInt("LaunchOriginalMotion",0));SessionState.SetBool("TouchlineLaunchSmoke",false);Debug.LogException(error);EditorApplication.Exit(1);}
        }
    }
}
