using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEngine.UIElements;

namespace Touchline.Editor
{
    [InitializeOnLoad] public static class MatchExperienceSmoke
    {
        static int stage,frames,last=-1,pausedEvaluations=-1,pausedFrames,analysisStage;static float analysisPress;static float[] analysisFitness;static bool performanceOpened,injuryStarted;static RenderTexture target;static string output;static Vector3[] positions;static string selectedPlayer;static int animations,previousMotion;
        static int foldStage,wallFrames;static VisualElement retainedProfile;
        static VisualElement Root=>TouchlineApp.Instance.GetComponent<UIDocument>().rootVisualElement;
        static MatchArena Arena=>UnityEngine.Object.FindFirstObjectByType<MatchArena>();
        static MatchExperienceSmoke(){EditorApplication.update+=Tick;}
        public static void Run(){ProjectBuilder.Configure();SessionState.SetBool("MatchExperienceSmoke",true);EditorApplication.isPlaying=true;}
        static void Click(string name){var b=Root.Query<Button>().ToList().FirstOrDefault(x=>x.text==name||x.name==name);if(b==null&&name!="Plus"){Click("Plus");b=Root.Query<Button>().ToList().FirstOrDefault(x=>x.text==name||x.name==name);}if(b==null)throw new Exception("Missing "+name);using(var e=NavigationSubmitEvent.GetPooled()){e.target=b;b.SendEvent(e);}}
        static void Resize(int w,int h){var old=target;target=new RenderTexture(w,h,24);target.Create();TouchlineApp.Instance.GetComponent<UIDocument>().panelSettings.targetTexture=target;if(old!=null){old.Release();UnityEngine.Object.DestroyImmediate(old);}}
        static void Capture(string name,bool expectPitch=false){var previous=RenderTexture.active;RenderTexture.active=target;var t=new Texture2D(target.width,target.height,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,target.width,target.height),0,0);t.Apply();var pixels=t.GetPixels();if(expectPitch){var surface=Root.Q<Image>("match-viewport");if(surface.image!=Arena.Viewport.Texture)throw new Exception("Viewport texture not bound");var b=surface.worldBound;float scale=target.width/Root.worldBound.width;var colours=new System.Collections.Generic.HashSet<int>();for(int y=(int)((Root.worldBound.height-b.yMax)*scale)+12;y<(Root.worldBound.height-b.yMin)*scale-12;y+=4)for(int x=(int)(b.xMin*scale)+12;x<b.xMax*scale-12;x+=4){if(x<0||x>=target.width||y<0||y>=target.height)continue;var c=pixels[y*target.width+x];colours.Add((int)(c.r*31)*1024+(int)(c.g*31)*32+(int)(c.b*31));}if(colours.Count<24)throw new Exception("Viewport is a flat placeholder, not a rendered stadium");}File.WriteAllBytes(Path.Combine(output,name+".png"),t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);RenderTexture.active=previous;if(expectPitch&&pixels.Count(c=>c.g>c.r*1.25f&&c.g>c.b*1.12f&&c.g>.08f)<pixels.Length*.08f)throw new Exception("Final interface hides the pitch: fewer than 8% turf pixels. No separate camera compositing is permitted in this check.");}
        static void CheckControls(){foreach(var b in Root.Q(className:"match-controls").Query<Button>().ToList())if(b.worldBound.yMax>Root.worldBound.yMax+1||b.worldBound.xMax>Root.worldBound.xMax+1||b.worldBound.height<43)throw new Exception("Match controls overflow");if(Arena.Viewport.Texture.width>1600||Arena.Viewport.Texture.height>1000)throw new Exception("Unbounded match texture");}
        static void CheckFingerTolerance(){var surface=Root.Q<Image>("match-viewport");bool near=false;foreach(var player in UnityEngine.Object.FindObjectsByType<PlayerView>(FindObjectsSortMode.None)){var point=Arena.MatchCamera.WorldToViewportPoint(player.transform.position+Vector3.up*.9f);if(point.z<=0||point.x<.05f||point.x>.95f||point.y<.05f||point.y>.95f)continue;var offset=new Vector2(point.x+12/surface.contentRect.width,point.y);if(!Physics.Raycast(Arena.MatchCamera.ViewportPointToRay(offset),270)&&Arena.Viewport.FindPlayerAt(offset)==player.PlayerId){near=true;break;}}if(!near)throw new Exception("Finger tolerance failed outside player collider");if(Arena.Viewport.FindPlayerAt(new Vector2(.01f,.99f))!=null)throw new Exception("Empty stadium should not select a distant player");}
        static void Tick(){if(!SessionState.GetBool("MatchExperienceSmoke",false)||!EditorApplication.isPlaying||TouchlineApp.Instance==null||last==Time.frameCount)return;last=Time.frameCount;if(++frames<24)return;frames=0;
            try{output=Path.GetFullPath("../../artifacts/unity/experience-0.15");Directory.CreateDirectory(output);var app=TouchlineApp.Instance;
                switch(stage++){
                    case 0:app.Career.EnsureWorld(app.Database);Resize(1280,966);Click("Bureau");break;
                    case 1:Capture("bureau");app.Career.life.day=app.Career.life.nextFixture;Click("Match");Click("Entrer sur le terrain");break;
                    case 2:Arena.Broadcast.Enabled=false;if(Root.Query<Button>().ToList().Any(b=>b.text=="Coup d’envoi"))Click("Coup d’envoi");else Arena.Paused=false;Arena.Speed=3;break;
                    case 3:Capture("match-open",true);int scenery=Arena.GetComponentsInChildren<Renderer>().Count(r=>r.enabled&&r.GetComponentInParent<PlayerView>()==null);if(scenery>20)throw new Exception("Static stadium renderers exceed mobile budget: "+scenery);Debug.Log("TOUCHLINE_SCENERY_RENDERERS "+scenery);var skinned=Arena.GetComponentsInChildren<SkinnedMeshRenderer>(true);if(skinned.Length!=24||skinned.Count(r=>r.name=="Skinned anatomy")!=22||skinned.Count(r=>r.name=="Keeper gloves"&&r.enabled)!=2)throw new Exception("Expected 22 player bodies and two active keeper glove meshes");if(app.Career.match.clock<=0)throw new Exception("Match did not advance");positions=UnityEngine.Object.FindObjectsByType<PlayerView>(FindObjectsSortMode.None).OrderBy(v=>v.PlayerId).Select(v=>v.transform.position).ToArray();break;
                    case 4:var views=UnityEngine.Object.FindObjectsByType<PlayerView>(FindObjectsSortMode.None).OrderBy(v=>v.PlayerId).ToArray();if(!views.Where((v,i)=>Vector3.Distance(v.transform.position,positions[i])>.01f).Any())throw new Exception("Players are frozen");Arena.Paused=true;var surface=Root.Q<Image>("match-viewport");bool picked=false;Physics.SyncTransforms();foreach(var view in views){var uv=Arena.MatchCamera.WorldToViewportPoint(view.transform.position+Vector3.up*.9f);if(uv.z<=0||uv.x<.05f||uv.x>.95f||uv.y<.05f||uv.y>.95f)continue;var ray=Arena.MatchCamera.ViewportPointToRay(uv);if(!Physics.Raycast(ray,out var hit,270)||hit.collider.GetComponentInParent<PlayerView>()!=view)continue;selectedPlayer=view.PlayerId;var point=surface.LocalToWorld(new Vector2(uv.x*surface.resolvedStyle.width,(1-uv.y)*surface.resolvedStyle.height));using(var down=PointerDownEvent.GetPooled(new Event{type=EventType.MouseDown,button=0,mousePosition=point})){down.target=surface;surface.SendEvent(down);}using(var up=PointerUpEvent.GetPooled(new Event{type=EventType.MouseUp,button=0,mousePosition=point})){up.target=surface;surface.SendEvent(up);}picked=true;break;}if(!picked)throw new Exception("No visible pickable player");break;
                    case 5:if(pausedEvaluations<0){pausedEvaluations=Arena.PoseEvaluations;pausedFrames=app.GetComponent<RenderBudget>().MatchFrames.count;stage--;break;}if(Arena.PoseEvaluations!=pausedEvaluations)throw new Exception("Paused skeletons still evaluated every frame");if(pausedFrames==0||app.GetComponent<RenderBudget>().MatchFrames.count!=pausedFrames)throw new Exception("Match performance sample includes paused frames or is empty");if(!Root.Q(className:"modal-panel").Query<Label>().ToList().Any(l=>l.text==app.Database.Find(selectedPlayer).name))throw new Exception("Wrong player profile");if(foldStage==0){Capture("match-player");Click("Attributs");retainedProfile=Root.Q("player-profile");foldStage++;stage--;break;}
                        if(foldStage==1){Resize(1080,2520);foldStage++;stage--;break;}
                        if(foldStage==2){if(Root.Q("player-profile")!=retainedProfile||!retainedProfile.Query<Button>(className:"active").ToList().Any(b=>b.text=="Attributs"))throw new Exception("Fold discarded player profile or selected tab");Capture("profile-folded");Resize(1280,966);foldStage++;stage--;break;}
                        if(Root.Q("player-profile")!=retainedProfile||!Arena.Paused)throw new Exception("Unfold discarded profile or resumed match");Click("Fermer");CheckFingerTolerance();Click("Tactique");break;
                    case 6:Capture("match-tactics");Click("tactics-return-match");break;
                    case 7:Capture("match-after-tactics",true);if(Root.Q<Button>("match-playback").text!="Reprendre")throw new Exception("Paused match should offer Reprendre");Arena.Viewport.Texture.Release();break;
                    case 8:if(!Arena.Viewport.Texture.IsCreated())throw new Exception("Lost render texture not restored");Capture("match-recovered",true);Resize(1080,2520);break;
                    case 9:
                        if(analysisStage==0){Capture("match-portrait",true);CheckControls();Click("Analyse");analysisStage++;stage--;break;}
                        if(analysisStage==1){var stats=Root.Query<VisualElement>(className:"match-stat").ToList();if(stats.Count<10)throw new Exception("Match statistics missing");var possession=stats.First(r=>r.Q<Label>().text=="Possession").Query<Label>(className:"match-stat-value").ToList();if(possession.Sum(l=>int.Parse(l.text.Replace("%","").Trim()))!=100)throw new Exception("Possession percentages do not sum to 100");var line=stats.First(r=>r.Q<Label>().text=="Ligne depuis son propre but").Query<Label>(className:"match-stat-value").ToList();if(app.Career.match.metrics[0].defensiveSamples==0&&line[0].text!="—")throw new Exception("Missing observations shown as real defensive position");Capture("analysis-portrait");Click("Temps forts");analysisStage++;stage--;break;}
                        if(analysisStage==2){var moment=Root.Query<Button>(className:"moment-profile").ToList().FirstOrDefault();if(moment==null)throw new Exception("Timeline has no player link");Capture("analysis-timeline");Click(moment.text);analysisStage++;stage--;break;}
                        if(analysisStage==3){if(Root.Q("player-profile")==null)throw new Exception("Timeline did not open a profile");Click("Retour à l’analyse");analysisStage++;stage--;break;}
                        if(analysisStage==4){if(Root.Query<Button>(className:"active").ToList().All(b=>b.text!="Temps forts"))throw new Exception("Timeline context not restored");analysisPress=app.Career.tactic.pressing;analysisFitness=app.Career.match.actors.Select(a=>a.fitness).ToArray();app.Career.tactic.pressing=.9f;foreach(var actor in app.Career.match.actors.Where(a=>a.side==0))actor.fitness=65;Click("Adjoint");analysisStage++;stage--;break;}
                        if(analysisStage==5){Capture("analysis-coach");Click("Appliquer ce conseil");analysisStage++;stage--;break;}
                        if(app.Career.match.homeTactic.pressing!=.45f)throw new Exception("Live staff advice not applied");app.Career.tactic.pressing=analysisPress;for(int i=0;i<analysisFitness.Length;i++)app.Career.match.actors[i].fitness=analysisFitness[i];Click("Fermer");Resize(1600,700);break;
                    case 10:if(!performanceOpened){Capture("match-landscape",true);CheckControls();Click("Options du match");Click("Fluidité du match");performanceOpened=true;stage--;break;}
                        if(!injuryStarted){if(!Root.Q(className:"modal-panel").Query<Label>().ToList().Any(l=>l.text.Contains("images/s en moyenne")))throw new Exception("Match performance panel missing actual samples");Capture("match-performance");Click("Fermer");var hurt=app.Career.match.actors[9];hurt.injured=true;app.Career.match.events.Add(new Touchline.Core.MatchEvent{kind="injury",side=0,player=hurt.id,time=app.Career.match.clock,text="Le joueur demande le staff médical."});injuryStarted=true;stage--;break;}
                        if(Root.Q("match-medical-alert")==null||!Arena.Paused)throw new Exception("Medical event did not pause and show staff message");Capture("match-medical-alert");Click("Préparer un remplacement");if(Root.Q("tactical-slot-9")?.ClassListContains("selected-player")!=true)throw new Exception("Injured player not selected for replacement");Click("tactics-return-match");Click("Bureau");break;
                    case 11:Click("Plus");break;
                    case 12:Capture("directory");Root.Q<TextField>("directory-search").value="contrat";Resize(1080,2520);break;
                    case 13:if(Root.Q<TextField>("directory-search")?.value!="contrat")throw new Exception("Rotation discarded search input");var results=Root.Query<Button>(className:"directory-entry").ToList();if(results.Count!=1||results[0].text!="Recrutement")throw new Exception("Directory search failed");Capture("directory-search");animations=app.InterfaceAnimationCount;Click("Recrutement");if(app.InterfaceAnimationCount<=animations||Root.Q(className:"content").style.opacity.value>=1)throw new Exception("Navigation animation did not start");break;
                    case 14:Resize(1600,700);if(Root.Q(className:"content").resolvedStyle.opacity<.99f)throw new Exception("Navigation animation did not finish");Click("Formation");break;
                    case 15:Click("history-back");break;
                    case 16:if(!Root.Query<Label>().ToList().Any(l=>l.text=="La cellule de recrutement"))throw new Exception("Back failed");Click("history-forward");break;
                    case 17:if(!Root.Query<Label>().ToList().Any(l=>l.text=="La relève"))throw new Exception("Forward failed");Root.Q(className:"content").Q<ScrollView>().scrollOffset=new Vector2(0,220);break;
                    case 18:Click("Finances");break;
                    case 19:Click("history-back");break;
                    case 20:if(Root.Q(className:"content").Q<ScrollView>().scrollOffset.y<200)throw new Exception("Page scroll not restored");Click("Réglages");break;
                    case 21:previousMotion=PlayerPrefs.GetInt("reduce-motion",0);Root.Query<Toggle>().ToList().First(t=>t.label=="Réduire les animations de l’interface").value=true;animations=app.InterfaceAnimationCount;Click("Bureau");if(app.InterfaceAnimationCount!=animations)throw new Exception("Reduced motion ignored");break;
                    case 22:Capture("bureau-landscape");PlayerPrefs.SetInt("reduce-motion",previousMotion);Resize(1280,966);Click("Match");break;
                    case 23:var restart=app.Career.match;restart.phase="free-kick";restart.restart=25;restart.restartSide=0;restart.restartTaker=null;restart.indirectRestart=false;restart.ball=new Touchline.Core.BallState{position=new Touchline.Core.Point(30,2),previous=new Touchline.Core.Point(30,2),side=0,lastTouch=0};Arena.Paused=true;Arena.Simulation.Advance(18);break;
                    case 24:if(wallFrames++<2){stage--;break;}foreach(float post in new[]{-3.66f,3.66f}){var goal=Arena.MatchCamera.WorldToViewportPoint(new Vector3(Arena.Simulation.Direction(0)*52.5f,2.44f,post));if(goal.z<=0||goal.x<0||goal.x>1||goal.y<0||goal.y>1)throw new Exception("Free kick camera cuts off goal");}if(app.Career.match.restartWall.Count<3)throw new Exception("Free kick wall missing");Capture("match-free-kick-wall",true);File.WriteAllText(Path.Combine(output,"report.json"),"{\"passed\":true,\"finalCompositedPitchVisible\":true,\"movingPlayers\":true,\"playerTapProfile\":true,\"returnFromTactics\":true,\"renderTextureRecovery\":true,\"portraitLandscape\":true,\"directorySearch\":true,\"backForward\":true,\"scrollMemory\":true,\"navigationAnimation\":true,\"reducedMotion\":true,\"physicalAndroid\":false}");SessionState.SetBool("MatchExperienceSmoke",false);Debug.Log("TOUCHLINE_EXPERIENCE_OK");EditorApplication.Exit(0);break;
                }
            }catch(Exception e){SessionState.SetBool("MatchExperienceSmoke",false);Debug.LogException(e);EditorApplication.Exit(1);}
        }
    }
}

