using System;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using Touchline.Core;

namespace Touchline.Tests
{
    public partial class ProfessionalTests
    {
        [Test] public void MonthlySalaryPreservesAnnualCost(){Assert.AreEqual(52000,Career.MonthlySalary(12000));Assert.AreEqual(12000,Career.WeeklySalary(52000));}
        [Test] public void SummerWindowStartsAtCareerOpening(){Assert.AreEqual(new DateTime(2026,6,15),c.Date);Assert.IsTrue(c.WindowOpen);}
        [Test] public void OutgoingLoanNeedsAgreementAndUsesSalaryPercentage(){long payroll=c.Payroll(db);c.ProposeOutgoingLoan(db,"p10","c1",0,new MarketTerms{loanWagePercent=80,loanEndDay=100,recall=true});Assert.Throws<InvalidOperationException>(()=>c.SignOutgoingLoan(db,"p10"));Days(2);c.SignOutgoingLoan(db,"p10");Assert.AreEqual("c1",db.Find("p10").team);Assert.AreEqual(payroll-400,c.Payroll(db));c.RecallLoan(db,"p10");Assert.AreEqual(c.club,db.Find("p10").team);Assert.AreEqual(payroll,c.Payroll(db));}
        [Test] public void OutgoingLoanObligationCannotAlsoBeRecalled(){Assert.Throws<ArgumentException>(()=>c.ProposeOutgoingLoan(db,"p10","c1",0,new MarketTerms{loanEndDay=100,obligationFee=100000,recall=true}));}
        [Test] public void StaffOwnershipSurvivesManagerChange(){c.EnsureStaffMarket(db);var old=c.Staff("assistant");c.approaches.Add(new JobApproach{club="c1",until=14});c.AnswerApproach(db,"c1",true);c.EnsureStaffMarket(db);Assert.AreNotEqual(old.id,c.Staff("assistant").id);Assert.AreEqual("c0",old.club);}
        [Test] public void LoanSalaryShareIsUsedInPayroll(){long before=c.Payroll(db);c.ProposeTransfer(db,"p24",100000,500,2,"rotation",true,terms:new MarketTerms{loanWagePercent=40,loanEndDay=100});Days(2);c.SignTransfer(db,"p24");Assert.AreEqual(before+200,c.Payroll(db));}
        [Test] public void InstalmentsChargeOnlyTheirOwnClub(){c.payments.Add(new PaymentDue{club="c1",amount=999999,label="Other club",due=1});Days(1);Assert.IsFalse(c.payments[0].settled);}
        [Test] public void TransferInstalmentsRemainReserved(){c.ProposeTransfer(db,"p24",120000,600,3,"starter",terms:new MarketTerms{upfrontPercent=50,instalments=2});Days(2);long cash=c.life.cash;c.SignTransfer(db,"p24");Assert.AreEqual(61200,cash-c.life.cash);Assert.AreEqual(60000,c.payments.Sum(p=>p.amount));Assert.AreEqual(120000,c.world.transferSpent);}
        [Test] public void FailedOptionCannotTakeMoney(){c.ProposeTransfer(db,"p24",100000,500,2,"rotation",true,terms:new MarketTerms{loanWagePercent=40,loanEndDay=100,optionFee=100000});Days(2);c.SignTransfer(db,"p24");c.life.cash=0;Assert.Throws<InvalidOperationException>(()=>c.ExerciseLoanOption(db,"p24"));Assert.AreEqual(0,c.life.cash);Assert.AreEqual("c1",c.Contract(db,"p24").parent);}
        [Test] public void PrecontractDoesNotMovePlayerBeforeExpiry(){var contract=c.Contract(db,"p24");contract.until=10;c.ProposeTransfer(db,"p24",0,600,3,"starter",precontract:true);Days(2);c.SignTransfer(db,"p24");Assert.AreEqual("c1",db.Find("p24").team);Assert.AreEqual(600,c.ReservedWages);Days(8);Assert.AreEqual("c1",db.Find("p24").team);Days(1);Assert.AreEqual(c.club,db.Find("p24").team);Assert.AreEqual(0,c.ReservedWages);}
        [Test] public void PrecontractCannotBeDuplicated(){c.Contract(db,"p24").until=30;c.ProposeTransfer(db,"p24",0,600,3,"starter",precontract:true);Days(2);c.SignTransfer(db,"p24");Assert.Throws<InvalidOperationException>(()=>c.ProposeTransfer(db,"p24",0,600,3,"starter",precontract:true));}
        [Test] public void SixMonthBoundaryUsesCalendarMonths(){c.Contract(db,"p24").until=(int)(c.Date.AddMonths(6)-Career.Epoch).TotalDays;Assert.IsTrue(c.CanPrecontract(db,"p24"));c.Contract(db,"p24").until++;Assert.IsFalse(c.CanPrecontract(db,"p24"));}
        [Test] public void FreePlayerSignsWithoutTransferFee(){var p=db.Find("p24");p.team="free";var employment=c.Contract(db,p.id);employment.club="free";employment.until=0;c.ProposeTransfer(db,p.id,0,p.wage*2,2,"rotation");Days(2);c.SignTransfer(db,p.id);Assert.AreEqual(c.club,p.team);Assert.AreEqual(0,c.world.transferSpent);}
        [Test] public void StaffDismissalPaysCompensationAndLeavesVacancy(){c.EnsureStaffMarket(db);var member=c.Staff("assistant");long cost=c.StaffReleaseCost(member),cash=c.life.cash;c.FireStaff(db,member.id);Assert.AreEqual(cost,cash-c.life.cash);c.EnsureStaffMarket(db);Assert.AreEqual(0,c.Staff("assistant").wage);Assert.IsNull(member.club);}
        [Test] public void StaffHireRequiresAgreementAndVacantRole(){c.EnsureStaffMarket(db);var member=c.staffMarket.First(s=>s.club==null&&s.role=="assistant");c.ProposeStaffContract(db,member.id,Career.MonthlySalary(member.wage*2),2);Assert.Throws<InvalidOperationException>(()=>c.SignStaffContract(db,member.id));Days(2);Assert.Throws<InvalidOperationException>(()=>c.SignStaffContract(db,member.id));c.FireStaff(db,c.Staff("assistant").id);c.SignStaffContract(db,member.id);Assert.AreEqual(member.id,c.Staff("assistant").id);Assert.Throws<InvalidOperationException>(()=>c.SignStaffContract(db,member.id));}
        [Test] public void ExpiredStaffDoesNotRegenerate(){c.EnsureStaffMarket(db);c.Staff("assistant").until=1;Days(1);c.EnsureStaffMarket(db);Assert.AreEqual(0,c.Staff("assistant").wage);}
        [Test] public void DelegatedTrainingRespondsToFatigue(){c.SetDelegation("training",true);foreach(var p in c.life.players)p.fitness=65;Days(1);Assert.AreEqual("rest",c.life.training);}
        [Test] public void ManualTrainingIsNotOverwritten(){c.life.training="heavy";Days(1);Assert.AreEqual("heavy",c.life.training);}
        [Test] public void VacantPhysicalCoachCannotManageTraining(){c.EnsureStaffMarket(db);c.SetDelegation("training",true);c.FireStaff(db,c.Staff("fitness").id);c.life.training="heavy";Days(1);Assert.AreEqual("heavy",c.life.training);}
        [Test] public void DelegationSurvivesSave(){c.SetDelegation("youth",true);var saved=JsonUtility.FromJson<Career>(JsonUtility.ToJson(c));saved.EnsureStaffMarket(db);Assert.IsTrue(saved.life.staff.youth);Assert.AreEqual(c.Staff("assistant").id,saved.Staff("assistant").id);}
        [Test] public void TacticalAdviceDependsOnActualFatigueAndChangesInstruction(){foreach(var id in c.lineup)db.Find(id).fitness=65;c.tactic.pressing=.9f;Assert.IsTrue(c.TacticalReport(db).Any(a=>a.key=="pressing"));c.ApplyStaffAdvice(db,"pressing");Assert.AreEqual(.45f,c.tactic.pressing);}
        [Test] public void LiveAdviceUsesMatchFatigueAndAppliesToLiveTactic(){foreach(var id in c.lineup)db.Find(id).fitness=100;c.match=MatchSimulation.Create(db,c,"c1").State;foreach(var actor in c.match.actors.Where(a=>a.side==0))actor.fitness=65;c.tactic.pressing=.9f;Assert.IsTrue(c.TacticalReport(db).Any(a=>a.key=="pressing"));c.ApplyStaffAdvice(db,"pressing");Assert.AreEqual(.45f,c.match.homeTactic.pressing);Assert.AreSame(c.tactic,c.match.homeTactic);}
        [Test] public void CentralDefenderAdviceUsesTheirActualPositions(){c.EnsureStaffMarket(db);c.Staff("assistant").tactics=18;c.tactic.line=.9f;for(int i=0;i<11;i++)db.Find(c.lineup[i]).attributes=new[]{new AttributeValue{key="sprintSpeed",value=c.tactic.withoutBall[i].role=="CB"?90:30}};Assert.IsFalse(c.TacticalReport(db).Any(a=>a.key=="line"));for(int i=0;i<11;i++)if(c.tactic.withoutBall[i].role=="CB")db.Find(c.lineup[i]).attributes[0].value=40;Assert.IsTrue(c.TacticalReport(db).Any(a=>a.key=="line"));}
        [Test] public void VacantAssistantDoesNotInventAdvice(){c.EnsureStaffMarket(db);c.Staff("assistant").wage=0;c.tactic.width=.95f;c.tactic.directness=.1f;Assert.IsEmpty(c.TacticalReport(db));}
        [Test] public void SuspendedManagerCannotApplyLiveAdvice(){c.match=MatchSimulation.Create(db,c,"c1").State;c.life.managerBanUntil=c.life.day+3;Assert.Throws<InvalidOperationException>(()=>c.ApplyStaffAdvice(db,"width"));}
        [Test] public void BetterStaffAddsDetailWithoutInventingAnotherSquad(){c.EnsureStaffMarket(db);c.tactic.pressing=.9f;c.tactic.line=.9f;c.tactic.tempo=.9f;c.tactic.width=.9f;c.tactic.directness=.1f;foreach(var id in c.lineup)db.Find(id).fitness=65;c.Staff("assistant").tactics=6;var low=c.TacticalReport(db);c.Staff("assistant").tactics=18;var high=c.TacticalReport(db);Assert.Greater(high.Count,low.Count);Assert.Greater(high[0].confidence,low[0].confidence);}
        [Test] public void CampCannotBeBookedTwiceButReturnsNextSeason(){c.ScheduleCamp("local",7);Assert.Throws<InvalidOperationException>(()=>c.ScheduleCamp("local",14));c.world.year++;c.life.day=365;c.ScheduleCamp("local",372);Assert.AreEqual(2,c.camps.Count);}
        [Test] public void FriendlyInvitationAddsOneCalendarMatch(){c.InviteFriendly(db,"c1",14,true);Days(2);Assert.AreEqual(1,c.world.fixtures.Count(f=>f.league=="friendly"));Days(1);Assert.AreEqual(1,c.world.fixtures.Count(f=>f.league=="friendly"));}
        [Test] public void FriendlyConflictIsRefusedWithoutSpendingGuarantee(){c.InviteFriendly(db,"c1",14,true);c.world.fixtures.Add(new Fixture{id="conflict",home="c1",away="c2",day=14,league="fra.1",published=true});long cash=c.life.cash;Days(2);Assert.AreEqual("declined",c.friendlies[0].status);Assert.AreEqual(cash,c.life.cash);}
        [Test] public void ShadowAdvanceIsRepaidEvenWithoutSanction(){c.life.corruptionEnabled=true;var investigation=new IntegrityCase{kind="shadow",opened=0,due=1,benefit=100000,cost=5000,accepted=true};c.life.investigations.Add(investigation);long cash=c.life.cash;Days(1);Assert.IsTrue(investigation.repaid);Assert.LessOrEqual(c.life.cash,cash-100000);}
        [Test] public void CooperationCannotEraseTheOffence(){c.life.corruptionEnabled=true;c.StartScheme("leak");Days(3);c.RespondIntegrity(0,"cooperate");c.life.corruptionEnabled=false;Days(2);Assert.AreEqual("sanctioned",c.life.investigations[0].status);Assert.Greater(c.life.managerBanUntil,c.life.day);}
        [Test] public void IntegrityAlertCannotBeFarmed(){c.life.corruptionEnabled=true;c.StartScheme("pressure");Days(3);c.RespondIntegrity(0,"ignore");Assert.Throws<InvalidOperationException>(()=>c.RespondIntegrity(0,"protect"));}
        [Test] public void NationalCupIncludesLoadedDivisionsWithoutReserves(){var cup=c.world.cups.Single(x=>x.id=="cup-fra");Assert.AreEqual(8,cup.entrants.Count);Assert.IsTrue(c.world.fixtures.Where(f=>f.league==cup.id).All(f=>f.knockout));Assert.AreEqual("Coupe de France",c.CompetitionName(db,cup.id));}
        [Test] public void NationalCupCompletesWithOneWinnerAndSevenTies(){var cup=c.world.cups.Single(x=>x.id=="cup-fra");for(int i=0;i<350&&!cup.finished;i++)Days(1);Assert.IsTrue(cup.finished);Assert.AreEqual(1,c.world.honours.Count(h=>h.competition==cup.id));Assert.AreEqual(7,c.world.fixtures.Count(f=>f.league==cup.id));}
    }
}
