using System;
using System.Linq;
using NUnit.Framework;
using Touchline.Core;
namespace Touchline.Tests {
 public class MessageDecisionContextTests {
  Career c;
  [SetUp] public void Setup(){c=new Career{club="a",world=new CareerWorld(),life=new ClubLife{day=0,nextFixture=int.MaxValue,cash=1000000}};c.world.sponsors.Add(new CommercialDeal{name="Horizon · maillot",slot="maillot",annual=100000});c.life.players.Add(new PlayerLife{id="p"});}
  [Test] public void EarlierDeadlineWinsOverNewerPinnedAgreement(){
   c.life.day=7;c.world.offers.Add(new TransferOffer{player="soon",destination="a",status="accepted",due=0});c.world.offers.Add(new TransferOffer{player="later",destination="a",status="accepted",due=7});
   var first=new ClubMessage{id=1,player="soon",action="transfer",subject="Accord de principe",day=0};var newer=new ClubMessage{id=2,player="later",action="transfer",subject="Accord de principe",day=7,pinned=true};
   Assert.AreSame(first,c.OrderedMessages(new[]{newer,first}).First());Assert.AreEqual(7,c.MessageDecisionDeadline(first));StringAssert.Contains("aujourd’hui",c.MessageDecisionTiming(first));c.world.offers[0].status="signed";Assert.AreSame(newer,c.OrderedMessages(new[]{first,newer}).First());
  }
  [Test] public void ReadingCommercialQuoteDoesNotSignOrCreateDeadline(){c.NegotiateSponsor(0,10000,2);var m=c.life.messages.Last();Assert.NotNull(m.reference);Assert.AreSame(c.world.sponsors[0],c.PendingCommercialAgreement(m));Assert.IsTrue(c.MessageNeedsDecision(m));Assert.IsNull(c.MessageDecisionDeadline(m));Assert.AreEqual("accepted",c.world.sponsors[0].status);Assert.AreEqual(0,c.world.sponsors[0].until);}
  [Test] public void CommercialSignatureResolvesOnlyTheActualQuoteAndBlocksSameSlot(){c.NegotiateSponsor(0,10000,2);var first=c.life.messages.Last();c.world.sponsors.Add(new CommercialDeal{name="Alto · maillot",slot="maillot",annual=100000});c.NegotiateSponsor(1,9000,2);var other=c.life.messages.Last();c.SignSponsor(0);Assert.IsFalse(c.MessageNeedsDecision(first));Assert.IsFalse(c.MessageNeedsDecision(other));Assert.AreEqual("accepted",c.world.sponsors[1].status);}
  [Test] public void OldCommercialMailDoesNotActivateAChangedQuote(){c.NegotiateSponsor(0,10000,2);var old=c.life.messages.Last();c.life.day=3;c.NegotiateSponsor(0,9000,3);Assert.IsFalse(c.MessageNeedsDecision(old));Assert.IsTrue(c.MessageNeedsDecision(c.life.messages.Last()));}
  [Test] public void LegacyCommercialMatchingRequiresItsOriginalNegotiationDay(){c.NegotiateSponsor(0,10000,2);var old=c.life.messages.Last();old.reference=null;Assert.IsTrue(c.MessageNeedsDecision(old));c.life.day=3;c.NegotiateSponsor(0,9000,2);Assert.IsFalse(c.MessageNeedsDecision(old));}
  [Test] public void CommercialCounterproposalIsAChoiceRatherThanImplicitAcceptance(){c.NegotiateSponsor(0,1000000,2);var m=c.life.messages.Last();Assert.AreEqual("counter",c.world.sponsors[0].status);Assert.IsTrue(c.MessageNeedsDecision(m));Assert.AreEqual("counter",c.world.sponsors[0].status);}
  [Test] public void FormerClubCommercialQuoteIsNotManagersDecision(){c.NegotiateSponsor(0,10000,2);var m=c.life.messages.Last();c.world.managerStatus="dismissed";Assert.IsFalse(c.MessageNeedsDecision(m));Assert.AreEqual("accepted",c.world.sponsors[0].status);}
  [Test] public void JobApproachCanBeDeclinedWhileUnemployed(){var offer=new JobApproach{club="b",offered=0,until=14};c.approaches.Add(offer);var m=new ClubMessage{action="jobs",reference="manager-approach/b/0/14"};c.world.managerStatus="dismissed";Assert.IsTrue(c.MessageNeedsDecision(m));Assert.AreEqual(14,c.MessageDecisionDeadline(m));c.AnswerApproach(null,"b",false);Assert.IsFalse(c.MessageNeedsDecision(m));Assert.AreEqual("declined",offer.status);}
  [Test] public void HistoricalApproachDoesNotReactivateForSameClub(){c.approaches.Add(new JobApproach{club="b",offered=0,until=14,status="expired"});c.approaches.Add(new JobApproach{club="b",offered=30,until=44});c.life.day=30;Assert.IsFalse(c.MessageNeedsDecision(new ClubMessage{action="jobs",reference="manager-approach/b/0/14"}));Assert.IsTrue(c.MessageNeedsDecision(new ClubMessage{action="jobs",reference="manager-approach/b/30/44"}));}
  [Test] public void AmbiguousLegacyApproachDoesNotChooseTheWrongClub(){c.approaches.Add(new JobApproach{club="b",offered=0,until=14});c.approaches.Add(new JobApproach{club="d",offered=0,until=14});Assert.IsNull(c.PendingJobApproach(new ClubMessage{action="jobs",sender="Agent • carrière",subject="Approche de B",day=0}));}
  [Test] public void FulfilledPromiseDoesNotRaiseRoutineMailPriority(){var p=c.Person("p");p.promiseUntil=2;p.promiseStarts=0;p.appearances=1;var m=new ClubMessage{player="p",action="talk",subject="Ancien échange"};Assert.AreEqual(2,c.MessagePriority(m));p.appearances=2;Assert.AreEqual(0,c.MessagePriority(m));}
  [Test] public void ExpiredApproachDoesNotMutateItsStatusWhenRead(){var o=new JobApproach{club="b",offered=0,until=14};c.approaches.Add(o);c.life.day=15;Assert.IsFalse(c.MessageNeedsDecision(new ClubMessage{action="jobs",reference="manager-approach/b/0/14"}));Assert.AreEqual("open",o.status);}
  [Test] public void ReferenceScopesCommercialQuoteToOriginalClub(){c.NegotiateSponsor(0,10000,2);var m=c.life.messages.Last();c.club="b";Assert.IsFalse(c.MessageNeedsDecision(m));Assert.AreEqual("accepted",c.world.sponsors[0].status);}
  [Test] public void MedicalDeadlineDescribesFallbackWithoutResolvingInjury(){c.life.day=4;c.life.medical.Add(new MedicalCase{id=2,player="p",opened=3,treatment="pending",remaining=7});var m=new ClubMessage{action="medical",player="p",reference="medical/2"};Assert.AreEqual(5,c.MessageDecisionDeadline(m));StringAssert.Contains("soins conservateurs",c.MessageDecisionTiming(m));Assert.AreEqual("pending",c.life.medical[0].treatment);}
  [Test] public void PromisePresentationDistinguishesFulfilledAndExtendedWithoutMutatingState(){var p=c.Person("p");p.promiseUntil=21;p.appearances=1;c.life.medical.Add(new MedicalCase{player="p",remaining=5});StringAssert.Contains("prolongée",c.PlayerPromiseStatus("p"));Assert.IsFalse(c.PlayerPromiseFulfilled("p"));p.appearances=2;Assert.IsTrue(c.PlayerPromiseFulfilled("p"));StringAssert.Contains("Engagement tenu",c.PlayerPromiseStatus("p"));Assert.AreEqual(21,p.promiseUntil);Assert.AreEqual(0,p.promiseStarts);Assert.AreEqual(2,p.appearances);p.promiseUntil=-1;Assert.IsFalse(c.PlayerPromiseFulfilled("p"));StringAssert.Contains("Aucune promesse",c.PlayerPromiseStatus("p"));}
 }
}
