using System.Linq;
using NUnit.Framework;
using Touchline.Core;
using UnityEngine;

namespace Touchline.Tests
{
    public class MotionContinuityRegressionTests
    {
        [Test] public void ActualFullDurationGoalReactsImmediatelyAndThenReturnsToOrdinaryMovement()
        {
            var db=JsonUtility.FromJson<Database>(Resources.Load<TextAsset>("Data/database").text);
            var clubs=db.clubs.Where(c=>c.playable&&c.league=="eng.1").Take(2).ToArray();MatchSimulation match=null;MatchEvent goal=null;
            foreach(uint seed in new uint[]{13007,26014,39021}){
                var career=new Career{club=clubs[0].id};career.lineup=Career.Select(db,career.club,career.tactic);
                var candidate=MatchSimulation.Create(db,career,clubs[1].id,seed,2700);candidate.State.professionalRules=true;
                int seen=0;for(int tick=0;tick<54000&&!candidate.State.finished;tick++){
                    if(candidate.State.halfTime)candidate.ResumeHalf();candidate.Advance(.1);
                    for(;seen<candidate.State.events.Count;seen++){var e=candidate.State.events[seen];if(e.kind=="goal"&&candidate.State.actors.Any(a=>a.id==e.player&&a.side==e.side)){goal=e;match=candidate;break;}}
                    if(goal!=null)break;
                }
                if(goal!=null)break;
            }
            Assert.IsNotNull(goal,"The test must exercise a goal generated by the actual full-length engine");
            match.Advance(.8);var actor=match.State.actors.Single(a=>a.id==goal.player);var context=PlayerMotionContext.From(match.State,actor,1);
            Assert.AreEqual(2,context.reaction);Assert.That(context.reactionTime,Is.EqualTo(.8f).Within(.02f));Assert.Greater(match.State.restart,10,"Exercise the long restart, rather than the legacy 3-second countdown");
            var restored=JsonUtility.FromJson<MatchState>(JsonUtility.ToJson(match.State));Assert.IsTrue(context.Same(PlayerMotionContext.From(restored,restored.actors.Single(a=>a.id==goal.player),1)));
            var go=new GameObject("Natural scoring reaction");try{
                var view=go.AddComponent<PlayerView>();view.Build(db.Find(actor.id),actor.side,actor.slot,Color.white);
                var point=match.State.ball.position;view.Render(actor,1,1,new Vector3(point.x,match.State.ball.height,point.z),context);
                var joints=go.GetComponentsInChildren<Transform>();float span=Vector3.Distance(joints.Single(t=>t.name=="wrist.L").position,joints.Single(t=>t.name=="wrist.R").position);
                Assert.Greater(span,.75f,"The scorer must visibly open their arms immediately after scoring");
                Assert.Less(Vector3.Distance(go.transform.position,new Vector3(actor.position.x,0,actor.position.z)),.00001f,"The reaction must preserve the simulated root");
            }finally{Object.DestroyImmediate(go);}
            match.Advance(3);Assert.AreEqual(0,PlayerMotionContext.From(match.State,actor,1).reaction,"Do not hold a scoring pose during the remaining preparation countdown");
            TestContext.WriteLine($"Natural goal at {goal.time:0.0}s, scorer {goal.player}, full-duration restart {match.State.restart:0.0}s");
        }

        [TestCase(false)][TestCase(true)]
        public void PlantFromApproachRemainsStableThroughoutKickWindup(bool left)
        {
            var go=new GameObject("Approach support continuity");try{
                var view=go.AddComponent<PlayerView>();view.Build(new PlayerData{id="support-continuity",heightCm=182,preferredFoot=left?"Left":"Right"},0,9,Color.white);
                var actor=new Actor{id="support-continuity",slot=9,action="run",velocity=new Point(0,3.5f)};
                for(int frame=0;frame<50;frame++){actor.previous=actor.position;actor.position+=actor.velocity/60;view.Render(actor,1,1f/60);}
                var support=view.FootPosition(!left);actor.previous=actor.position;actor.velocity=new Point();actor.action="kick";actor.actionKind="pass";actor.actionSequence=1;
                var ball=new Vector3(actor.position.x,.11f,actor.position.z+.42f);actor.actionTarget=new Point(ball.x,ball.z);actor.actionHeight=ball.y;
                float maximumSlide=0;
                for(int frame=0;frame<=18;frame++){
                    actor.actionTime=.64f-frame*.01f;view.Render(actor,1,.01f,ball);
                    maximumSlide=Mathf.Max(maximumSlide,Vector3.ProjectOnPlane(view.FootPosition(!left)-support,Vector3.up).magnitude);
                    Assert.Greater(view.FootPosition(!left).y,.025f);
                }
                Assert.Less(maximumSlide,.20f,"The support sole must retain its approach placement instead of switching to the recording's plant point");
                Assert.Less(Vector3.Distance(view.InsideFootContactPosition(left),ball),.07f,"Support continuity must preserve the actual passing contact");
            }finally{Object.DestroyImmediate(go);}
        }

        [Test] public void ThighReceptionUsesTheRecordedImpactSideAfterTheBallHasDropped()
        {
            var go=new GameObject("Saved reception side");try{
                var view=go.AddComponent<PlayerView>();view.Build(new PlayerData{id="reception-side",heightCm=180,preferredFoot="Right"},0,9,Color.white);
                var actor=new Actor{id="reception-side",slot=9,action="run",velocity=new Point(0,2)};view.Render(actor,1,1f/60);
                actor.action="control";actor.actionKind=MatchSimulation.ThighControl;actor.actionSequence=1;actor.velocity=new Point();actor.actionTarget=new Point(.23f,.30f);actor.actionHeight=.95f;
                var impact=new Vector3(.23f,.95f,.30f);var currentBall=new Vector3(-.20f,.11f,.40f);
                for(int frame=0;frame<=8;frame++){actor.actionTime=MatchSimulation.BodyControlDuration(actor.actionKind)-frame*.01f;view.Render(actor,1,.01f,currentBall);}
                Assert.Less(Vector3.Distance(view.ThighContactPosition(true),impact),.13f,"Use the side of the saved body impact rather than the ball's later ground position");Assert.Greater(view.FootPosition(false).y,.025f);
            }finally{Object.DestroyImmediate(go);}
        }
    }
}
