using System;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using Touchline.Core;

namespace Touchline.Tests
{
    public partial class ProfessionalTests
    {
        Database db;Career c;
        [SetUp] public void Setup(){db=new Database{leagues=new[]{new LeagueData{id="fra.1",name="L1"},new LeagueData{id="fra.2",name="L2",tier=2}},clubs=Enumerable.Range(0,8).Select(i=>new ClubData{id="c"+i,name="Club "+i,league=i<4?"fra.1":"fra.2",playable=true,annualRevenue=20000000+i*1000000}).ToArray(),players=Enumerable.Range(0,8*24).Select(i=>new PlayerData{id="p"+i,name="Alex "+i,team="c"+(i/24),age=24,position=i%24==0||i%24==12?"GB":i%24<8?"DEF":i%24<16?"MIL":"ATT",positions=new[]{i%24==0||i%24==12?"GK":i%24<8?"CB":i%24<16?"CM":"ST"},rating=65,potential=80,value=100000,wage=500,fitness=100,morale=75,attributes=new[]{new AttributeValue{key="shortPassing",value=65},new AttributeValue{key="sprintSpeed",value=65}}}).ToArray()};c=new Career{club="c0"};c.lineup=Career.Select(db,c.club,c.tactic);c.EnsureWorld(db);}
        void Finish(){var f=c.NextFixture();if(f==null||f.day>c.life.day)return;c.PrepareLineup(db);var sim=MatchSimulation.Create(db,c,f.home==c.club?f.away:f.home);c.match=sim.State;c.world.activeFixture=f.id;c.ApplyMatchContext(sim);sim.State.finished=true;sim.State.clock=720;sim.State.score[0]=2;sim.State.score[1]=0;c.RecordMatch(db);c.match=null;}
        void Days(int count){for(int i=0;i<count;i++){Finish();c.AdvanceDay(db);}}
        [Test] public void GeneratedLeagueHasEachOrderedPairOnce(){var fixtures=c.world.fixtures.Where(f=>f.league=="fra.1").ToArray();Assert.AreEqual(12,fixtures.Length);Assert.AreEqual(12,fixtures.Select(f=>f.home+":"+f.away).Distinct().Count());}
        [Test] public void PublishedDatesSurviveCareerProgression(){db.fixtures=new[]{new Fixture{league="fra.1",home="c0",away="c1",date="2026-09-01T18:00Z",published=true,venue="Official stadium"},new Fixture{league="fra.1",home="c1",away="c0",date="2026-09-03T18:00Z",published=true}};c.world=null;c.EnsureWorld(db);Days(10);CollectionAssert.AreEquivalent(new[]{78,80},c.world.fixtures.Where(f=>f.published).Select(f=>f.day));}
        [Test] public void ResultsUpdateBothClubsOnce(){var f=c.world.fixtures.First(x=>x.league=="fra.1"&&!x.played);c.CommitFixture(f,3,1);var table=c.Table("fra.1");Assert.AreEqual(table.Sum(t=>t.gf),table.Sum(t=>t.ga));Assert.Throws<InvalidOperationException>(()=>c.CommitFixture(f,3,1));}
        [Test] public void HomeAndAwayResultsAreMappedToFixture(){var f=c.NextFixture();c.life.day=f.day;Finish();Assert.IsTrue(f.played);Assert.AreEqual(2,f.home==c.club?f.hg:f.ag);}
        [Test] public void ContinueDoesNotSkipACompetitionMatch(){c.life.day=c.life.nextFixture;Assert.Throws<InvalidOperationException>(()=>c.AdvanceDay(db));Finish();c.AdvanceDay(db);}
        [Test] public void ScoutKnowledgeArrivesProgressively(){c.Scout(db,"p24");Assert.AreEqual(0,c.Knowledge("p24"));Days(4);Assert.That(c.Knowledge("p24"),Is.InRange(1,89));Days(12);Assert.AreEqual(90,c.Knowledge("p24"));Assert.IsTrue(c.life.messages.Any(m=>m.action=="scout"&&m.subject=="Rapport disponible"));}
        [Test] public void RepeatedScoutAssignmentCannotSpendAgain(){c.Scout(db,"p24");long cash=c.life.cash;Assert.Throws<InvalidOperationException>(()=>c.Scout(db,"p24"));Assert.AreEqual(cash,c.life.cash);}
        [Test] public void TransferNeedsAcceptanceAndFinalConfirmation(){c.ProposeTransfer(db,"p24",120000,600,3,"starter");Assert.Throws<InvalidOperationException>(()=>c.SignTransfer(db,"p24"));Days(2);Assert.AreEqual("c1",db.Find("p24").team);c.SignTransfer(db,"p24");Assert.AreEqual(c.club,db.Find("p24").team);long cash=c.life.cash;Assert.Throws<InvalidOperationException>(()=>c.SignTransfer(db,"p24"));Assert.AreEqual(cash,c.life.cash);}
        [Test] public void PlayerTransferPersistsAcrossUnitySerialization(){c.ProposeTransfer(db,"p24",120000,600,3,"starter");Days(2);c.SignTransfer(db,"p24");var restored=JsonUtility.FromJson<Career>(JsonUtility.ToJson(c));db.Find("p24").team="c1";restored.RestoreWorld(db);restored.EnsureLife(db);Assert.AreEqual(c.club,db.Find("p24").team);Assert.IsTrue(restored.Available("p24"));}
        [Test] public void ContractConditionsCannotExceedLimits(){Assert.Throws<ArgumentException>(()=>c.ProposeTransfer(db,"p24",120000,600,6,"starter"));Assert.Throws<ArgumentException>(()=>c.ProposeTransfer(db,"p24",120000,-1,3,"starter"));Assert.Throws<InvalidOperationException>(()=>c.ProposeTransfer(db,"p24",c.TransferBudget+1,600,3,"starter"));}
        [Test] public void TransferBudgetIsCheckedAgainAtSignature(){c.ProposeTransfer(db,"p24",120000,600,3,"starter");Days(2);c.life.cash=0;Assert.Throws<InvalidOperationException>(()=>c.SignTransfer(db,"p24"));Assert.AreEqual("c1",db.Find("p24").team);}
        [Test] public void InternationalMinorTransfersAreExcluded(){db.Find("p24").age=17;Assert.Throws<InvalidOperationException>(()=>c.ProposeTransfer(db,"p24",120000,600,3,"starter"));}
        [Test] public void TicketInflationReducesDemandAndCannotBeRepeatedDaily(){float fill=c.Occupancy;c.SetTicketPrice(200);Assert.Less(c.Occupancy,fill);Assert.Throws<InvalidOperationException>(()=>c.SetTicketPrice(250));}
        [Test] public void SponsorshipCannotDoubleBookAnExclusiveSlot(){c.NegotiateSponsor(0,10000,2);c.SignSponsor(0);Assert.Throws<InvalidOperationException>(()=>c.SignSponsor(0));Assert.Throws<InvalidOperationException>(()=>c.NegotiateSponsor(1,10000,2));}
        [Test] public void YouthIntakeHasTwoGoalkeepersAndUniqueIdentities(){var youth=c.world.youth.Select(y=>db.Find(y.player)).ToArray();Assert.GreaterOrEqual(youth.Length,14);Assert.GreaterOrEqual(youth.Count(p=>p.Goalkeeper),2);Assert.AreEqual(db.players.Length,db.players.Select(p=>p.id).Distinct().Count());Assert.IsTrue(youth.All(p=>p.potential>=p.rating&&p.age>=16&&p.age<=17));}
        [Test] public void PromotionIsPersistentAndCannotDuplicatePlayer(){var id=c.world.youth[0].player;c.PromoteYouth(db,id);Assert.AreEqual(c.club,db.Find(id).team);Assert.Throws<InvalidOperationException>(()=>c.PromoteYouth(db,id));Assert.AreEqual(1,c.life.players.Count(p=>p.id==id));}
        [Test] public void LoanReturnsPlayerAndRestoresOriginalWage(){var id=c.world.youth[0].player;c.PromoteYouth(db,id);var p=db.Find(id);p.age=19;p.rating=70;long wage=p.wage;c.LoanYouth(db,id,"c4");c.Contract(db,id).loanUntil=c.life.day+3;Assert.AreEqual("c4",p.team);Days(3);Assert.AreEqual(c.club,p.team);Assert.AreEqual(wage,p.wage);Assert.IsTrue(c.Available(id));}
        [Test] public void PressConferenceCannotFarmMorale(){var f=c.NextFixture();c.life.day=f.day-1;c.Press("before","protect");float morale=c.Person(c.lineup[0]).morale;Assert.Throws<InvalidOperationException>(()=>c.Press("before","protect"));Assert.AreEqual(morale,c.Person(c.lineup[0]).morale);}
        [Test] public void ApproachMovesManagerWithoutResettingDateOrLeague(){c.life.day=50;c.approaches.Add(new JobApproach{club="c1",until=64});int count=c.world.fixtures.Count;long oldCash=c.life.cash;c.AnswerApproach(db,"c1",true);Assert.AreEqual(50,c.life.day);Assert.AreEqual("c1",c.club);Assert.AreEqual(count,c.world.fixtures.Count);Assert.AreEqual(oldCash,c.previousClubs.First(x=>x.club=="c0").life.cash);}
        [Test] public void ExpiredApproachCannotBeAccepted(){c.approaches.Add(new JobApproach{club="c1",until=-1});Assert.Throws<InvalidOperationException>(()=>c.AnswerApproach(db,"c1",true));Assert.AreEqual("c0",c.club);}
        [Test] public void ExclusionRemovesPlayerFromDecisionsAndCannotBeReplaced(){var sim=MatchSimulation.Create(db,c,"c1");var p=sim.State.actors[9];sim.Caution(p.id);sim.Caution(p.id);Assert.IsTrue(p.sentOff);Assert.Throws<InvalidOperationException>(()=>sim.Substitute(0,9,"p23"));sim.Advance(30);Assert.IsFalse(sim.State.ball.owner==p.id);Assert.AreEqual(0,p.velocity.Length);}
        [Test] public void DismissedGoalkeeperGetsAnEmergencyKeeper(){var sim=MatchSimulation.Create(db,c,"c1");string id=sim.State.actors[0].id;sim.SendOff(id);Assert.AreNotEqual(id,sim.State.actors[0].id);Assert.AreEqual(0,sim.State.actors[0].slot);sim.Advance(10);Assert.IsFalse(float.IsNaN(sim.State.ball.position.x));}
        [Test] public void InMatchInjuryCreatesOneMedicalSms(){var sim=MatchSimulation.Create(db,c,"c1");c.match=sim.State;c.match.events.Add(new MatchEvent{kind="injury",side=0,player=c.lineup[9]});c.ProcessMedicalEvents(db);c.ProcessMedicalEvents(db);Assert.AreEqual(1,c.life.medical.Count);Assert.AreEqual(1,c.life.messages.Count(m=>m.action=="medical"));}
        [Test] public void CapturedLocomotionContainsRealSourceFrames(){Assert.IsTrue(CapturedLocomotion.Available);var a=CapturedLocomotion.Sample(.1f,4);var b=CapturedLocomotion.Sample(.6f,4);Assert.AreNotEqual(a.leftArm,b.leftArm);Assert.IsFalse(float.IsNaN(a.leftLift));}
        [Test] public void CareerWorldSurvivesJsonRoundTrip(){var restored=JsonUtility.FromJson<Career>(JsonUtility.ToJson(c));restored.RestoreWorld(db);restored.EnsureWorld(db);Assert.AreEqual(c.world.fixtures.Count,restored.world.fixtures.Count);Assert.AreEqual(c.world.youth.Count,restored.world.youth.Count);Assert.AreEqual(c.NextFixture().id,restored.NextFixture().id);}
    }
}
