using System;
using System.Linq;
using NUnit.Framework;
using Touchline.Core;
using UnityEngine;

namespace Touchline.Tests
{
    public class SimulationTests
    {
        Database db;
        [SetUp] public void Setup(){db=new Database{schema=1,clubs=new[]{new ClubData{id="a",name="A",league="l",playable=true},new ClubData{id="b",name="B",league="l",playable=true}},players=Enumerable.Range(0,32).Select(i=>new PlayerData{id="p"+i,name="Player "+i,team=i<16?"a":"b",position=i%16==0?"GB":i%16<5?"DEF":i%16<8?"MIL":"ATT",positions=new[]{i%16==0?"GK":i%16<5?"CB":i%16<8?"CM":"ST"},rating=70,potential=80,fitness=100,morale=75}).ToArray()};}
        MatchSimulation Sim(uint seed=731){var c=new Career{club="a"};c.lineup=Career.Select(db,c.club,c.tactic);return MatchSimulation.Create(db,c,"b",seed);}
        [Test] public void ElevenDistinctPlayersWithGoalkeeper(){var s=Sim();Assert.AreEqual(22,s.State.actors.Select(a=>a.id).Distinct().Count());Assert.IsTrue(db.Find(s.State.actors[0].id).Goalkeeper);Assert.IsTrue(db.Find(s.State.actors[11].id).Goalkeeper);foreach(var a in s.State.actors)if(a!=s.State.actors[9])Assert.LessOrEqual(a.position.x*s.Direction(a.side),0);}
        [Test] public void FrameChunksDoNotChangeDecisions(){var a=Sim();var b=Sim();a.Advance(60);for(int i=0;i<1200;i++)b.Advance(.05);Assert.AreEqual(JsonUtility.ToJson(a.State),JsonUtility.ToJson(b.State));}
        [Test] public void OpenStrikerShootsInsteadOfPassingBack(){var sim=Sim();var m=sim.State;foreach(var a in m.actors)a.position=new Point(-20,a.slot*2);var striker=m.actors[9];striker.position=new Point(39,0);striker.angle=(float)Math.PI/2;m.actors[11].position=new Point(50,0);m.ball.owner=striker.id;m.ball.position=striker.position;Assert.AreEqual("shot",sim.Decide(striker));Assert.AreEqual("shot",m.ball.kind);}
        [Test] public void PatientAttackWaitsForBetterChanceAtEdgeOfBox(){foreach(bool patient in new[]{false,true}){var sim=Sim();var m=sim.State;foreach(var a in m.actors)a.position=new Point(-20,a.slot*2);var striker=m.actors[9];striker.position=new Point(33,0);striker.angle=(float)Math.PI/2;m.actors[11].position=new Point(51,0);m.ball.owner=striker.id;m.ball.position=striker.position;m.homeTactic.workIntoBox=patient;if(patient)Assert.AreNotEqual("shot",sim.Decide(striker));else Assert.AreEqual("shot",sim.Decide(striker));}}
        [Test] public void PatientAttackStillTakesClearCloseChance(){var sim=Sim();var m=sim.State;foreach(var a in m.actors)a.position=new Point(-20,a.slot*2);var striker=m.actors[9];striker.position=new Point(42,0);striker.angle=(float)Math.PI/2;m.actors[11].position=new Point(51,0);m.ball.owner=striker.id;m.ball.position=striker.position;m.homeTactic.workIntoBox=true;Assert.AreEqual("shot",sim.Decide(striker));}
        [Test] public void TightBylineAngleDoesNotTriggerAutomaticShot(){for(uint seed=1;seed<=20;seed++){var sim=Sim(seed);var m=sim.State;foreach(var a in m.actors)a.position=new Point(-20,a.slot*2);var striker=m.actors[9];striker.position=new Point(50.5f,12);m.actors[11].position=new Point(51.5f,2.5f);m.ball.owner=striker.id;m.ball.position=striker.position;Assert.AreNotEqual("shot",sim.Decide(striker));}}
        [Test] public void KeeperRetreatsGoalwardWhenAttackerReachesByline(){var sim=Sim();var m=sim.State;m.restart=0;m.decision=10;var striker=m.actors[9];striker.position=new Point(50.5f,12);m.ball.owner=striker.id;m.ball.position=striker.position;var keeper=m.actors[11];keeper.position=new Point(50,0);sim.Advance(.3);Assert.Greater(keeper.position.x,50);Assert.Greater(keeper.position.z,0);}
        [Test] public void BlockedPassLaneIsUnsafe(){var d=new Actor{position=new Point(6,.2f)};Assert.Less(MatchSimulation.LaneSafety(new Point(),new Point(12,0),new[]{d}),.35);Assert.Greater(MatchSimulation.LaneSafety(new Point(),new Point(12,-12),new[]{d}),.8);}
        [Test] public void HalfTimeStopsSimulationAndChangesDirection(){var sim=Sim();sim.Advance(400);Assert.AreEqual(360,sim.State.clock);Assert.IsTrue(sim.State.halfTime);sim.Advance(100);Assert.AreEqual(360,sim.State.clock);sim.ResumeHalf();Assert.AreEqual(-1,sim.Direction(0));sim.Advance(3.2);Assert.IsFalse(sim.State.halfTime);}
        [Test] public void MatchEndsWithScoreMatchingGoalEvents(){var sim=Sim();sim.Advance(360);sim.ResumeHalf();sim.Advance(360);Assert.IsTrue(sim.State.finished);Assert.AreEqual(90,sim.State.Minute);for(int side=0;side<2;side++)Assert.AreEqual(sim.State.score[side],sim.State.events.Count(e=>e.kind=="goal"&&e.side==side));Assert.Greater(sim.State.passes.Sum(),30);foreach(var a in sim.State.actors){Assert.IsFalse(float.IsNaN(a.position.x));Assert.LessOrEqual(Math.Abs(a.position.x),52.5);Assert.LessOrEqual(Math.Abs(a.position.z),34);}}
        [Test] public void SubstituteTransfersBallOwnershipAndCannotReenter(){var sim=Sim();var m=sim.State;var outgoing=m.actors[9].id;var p=db.players.First(p=>p.team=="a"&&!m.used.Contains(p.id));m.ball.owner=outgoing;sim.Substitute(0,9,p.id);Assert.AreEqual(p.id,m.ball.owner);Assert.AreEqual(p.id,m.actors[9].id);Assert.Throws<InvalidOperationException>(()=>sim.Substitute(0,9,outgoing));Assert.AreEqual(1,m.substitutions[0]);}
        [Test] public void ThreeReplacementWindowsAreEnforced(){var sim=Sim();for(int i=0;i<3;i++){sim.State.clock=i+10;sim.Substitute(0,8,db.players.First(p=>p.team=="a"&&!sim.State.used.Contains(p.id)).id);}sim.State.clock=25;var next=db.players.First(p=>p.team=="a"&&!sim.State.used.Contains(p.id)).id;Assert.Throws<InvalidOperationException>(()=>sim.Substitute(0,8,next));sim.State.halfTime=true;sim.Substitute(0,8,next);Assert.AreEqual(4,sim.State.substitutions[0]);}
        [Test] public void SaveReloadProducesSameContinuation(){var a=Sim();a.Advance(37.45);var copy=JsonUtility.FromJson<MatchState>(JsonUtility.ToJson(a.State));var b=new MatchSimulation(db,copy);Assert.AreEqual(JsonUtility.ToJson(a.State),JsonUtility.ToJson(b.State),"Restoring must not alter saved state");a.Advance(20);b.Advance(20);if(JsonUtility.ToJson(a.State)!=JsonUtility.ToJson(b.State)){System.IO.File.WriteAllText(System.IO.Path.GetFullPath("../../artifacts/unity/save-continuation-original.json"),JsonUtility.ToJson(a.State));System.IO.File.WriteAllText(System.IO.Path.GetFullPath("../../artifacts/unity/save-continuation-restored.json"),JsonUtility.ToJson(b.State));}Assert.AreEqual(JsonUtility.ToJson(a.State),JsonUtility.ToJson(b.State));}
        [Test] public void ChangingFormationKeepsSelectionAndPhasesIndependent(){var c=new Career{club="a"};c.lineup=Career.Select(db,"a",c.tactic);var before=c.lineup.ToArray();c.tactic.SetFormation("4-4-2");CollectionAssert.AreEqual(before,c.lineup);var without=c.tactic.withoutBall[9].x;c.tactic.withBall[9].x=18;Assert.AreEqual(without,c.tactic.withoutBall[9].x);}
        [Test] public void AllImportedClubsAndPlayersRemainAvailable(){var database=JsonUtility.FromJson<Database>(Resources.Load<TextAsset>("Data/database").text);var originalLeagues=database.leagues.Where(l=>!l.scoutingOnly).Select(l=>l.id).ToArray();var scoutingLeagues=database.leagues.Where(l=>l.scoutingOnly).Select(l=>l.id).ToArray();var originalClubs=database.clubs.Where(c=>!scoutingLeagues.Contains(c.league)).Select(c=>c.id).ToArray();Assert.AreEqual(21,originalLeagues.Length);Assert.AreEqual(429,originalClubs.Length,"Original clubs include 45 non-playable European entrants outside the original 21 divisions.");Assert.AreEqual(384,database.clubs.Count(c=>c.playable),"Playable club count must match the preserved baseline.");Assert.AreEqual(12641,database.players.Count(p=>originalClubs.Contains(p.team)));Assert.AreEqual(36,database.leagues.Length);Assert.AreEqual(715,database.clubs.Length);Assert.AreEqual(21815,database.players.Length);Assert.AreEqual(database.players.Length,database.players.Select(p=>p.id).Distinct().Count());foreach(var club in database.clubs.Where(c=>c.playable)){var ids=Career.Select(database,club.id,new Tactic());Assert.AreEqual(11,ids.Length,club.name);}}
        [Test] public void AdultMeshHasNormalizedWeights(){var source=JsonUtility.FromJson<HumanSource>(Resources.Load<TextAsset>("Models/footballer").text);Assert.That(source.height,Is.InRange(1.7f,1.95f));foreach(var part in source.parts)for(int i=0;i<part.skinWeight.Length;i+=4)Assert.That(part.skinWeight.Skip(i).Take(4).Sum(),Is.EqualTo(1).Within(.001));}
        void Possession(MatchSimulation sim,int side,Point ball){var m=sim.State;m.restart=0;m.phase="play";m.clock=100;m.turnoverAt=-100;m.decision=100;var owner=m.actors[side*11+6];owner.position=ball;owner.angle=sim.Direction(side)*(float)Math.PI/2;owner.carryTarget=ball+new Point(sim.Direction(side)*5,0);m.ball.owner=owner.id;m.ball.position=ball;m.ball.side=side;m.possessionSide=side;}
        [Test] public void CustomAttackingSlotSurvivesMovementLogic(){var sim=Sim();Possession(sim,0,new Point(0,0));sim.State.homeTactic.withBall[10].x=90;sim.Advance(.1);float wide=sim.MovementTarget(10).z;sim.State.homeTactic.withBall[10].x=55;sim.Advance(.1);Assert.Less(wide-sim.MovementTarget(10).z,-12);}
        [Test] public void DefensiveLineChangesTheWholeBlock(){var low=Sim();var high=Sim();Possession(low,1,new Point(10,20));Possession(high,1,new Point(10,20));low.State.homeTactic.line=.1f;high.State.homeTactic.line=.9f;low.Advance(.1);high.Advance(.1);float delta=Enumerable.Range(1,4).Average(i=>high.MovementTarget(i).x-low.MovementTarget(i).x);Assert.Greater(delta,10);}
        [Test] public void CounterPressChangesImmediateReactionToLoss(){var retreat=Sim();var press=Sim();foreach(var sim in new[]{retreat,press}){Possession(sim,1,new Point(-5,0));sim.State.turnoverAt=100;sim.State.actors[6].position=new Point(-9,0);sim.State.actors[7].position=new Point(-12,7);}press.State.homeTactic.counterPress=true;retreat.Advance(.1);press.Advance(.1);Assert.AreEqual("delay",retreat.State.actors[6].intent);Assert.AreEqual("press",press.State.actors[6].intent);Assert.Greater(Point.Distance(retreat.MovementTarget(6),retreat.State.ball.position),Point.Distance(press.MovementTarget(6),press.State.ball.position));}
        [Test] public void ReloadedCareerKeepsLiveTacticBinding(){var career=new Career{club="a"};career.lineup=Career.Select(db,"a",career.tactic);career.match=MatchSimulation.Create(db,career,"b").State;var copy=JsonUtility.FromJson<Career>(JsonUtility.ToJson(career));copy.BindMatchTactic();copy.tactic.line=.9f;Assert.AreSame(copy.tactic,copy.match.homeTactic);Assert.AreEqual(.9f,copy.match.homeTactic.line);}
        [Test] public void BallWaitsForTheKickContact(){var sim=Sim();Possession(sim,0,new Point(39,0));foreach(var a in sim.State.actors)if(a.side==1)a.position=new Point(-20,a.slot*3);var striker=sim.State.actors[6];Assert.AreEqual("shot",sim.Decide(striker));var origin=sim.State.ball.position;sim.Advance(.1);Assert.Less(Point.Distance(origin,sim.State.ball.position),.5f);Assert.Less(sim.State.ball.elapsed,0);sim.Advance(.2);Assert.Greater(sim.State.ball.position.x,origin.x+.65f);}
        [Test] public void RunnerBrakesBeforeReversingDirection(){var sim=Sim();Possession(sim,0,new Point());var p=sim.State.actors[6];foreach(var other in sim.State.actors)if(other!=p)other.position=other.previous=new Point(-40+other.side*80,-25+other.slot*4);p.velocity=new Point(5,0);p.carryTarget=new Point(-20,0);sim.Advance(.1);Assert.Greater(p.velocity.x,0);Assert.LessOrEqual(Math.Abs(5-p.velocity.x),1.1f,"Voluntary braking in clear space, without a body collision");}
        [Test] public void DeflectionAcrossGoalLineAwardsCornerToAttackingTeam(){var sim=Sim();Possession(sim,0,new Point());sim.State.ball.owner=null;sim.State.ball.kind="none";sim.State.ball.position=new Point(53,9);sim.State.ball.lastTouch=1;sim.Advance(.1);Assert.AreEqual("corner",sim.State.phase);Assert.AreEqual(0,sim.State.restartSide);Assert.AreEqual(1,sim.State.metrics[0].corners);}
        [Test] public void ThrowInReturnsToOpponentOfLastTouch(){var sim=Sim();Possession(sim,0,new Point());sim.State.ball.owner=null;sim.State.ball.kind="none";sim.State.ball.position=new Point(4,35);sim.State.ball.lastTouch=0;sim.Advance(.1);Assert.AreEqual("throw-in",sim.State.phase);Assert.AreEqual(1,sim.State.restartSide);}
        [Test] public void DifferentDutyChangesRunDepthWithoutMovingTheWideChannel(){var sim=Sim();Possession(sim,0,new Point(20,0));foreach(var a in sim.State.actors)if(a.side==1)a.position=new Point(50,a.slot*3-15);sim.State.homeTactic.withBall[5].duty="defend";sim.Advance(.1);var defend=sim.MovementTarget(5);sim.State.homeTactic.withBall[5].duty="attack";sim.Advance(.1);var attack=sim.MovementTarget(5);Assert.Greater(attack.x-defend.x,8);Assert.That(attack.z,Is.EqualTo(defend.z).Within(1));}
        [Test] public void MetricsRemainFiniteAndPassCompletionsCannotExceedAttempts(){var sim=Sim();sim.Advance(360);sim.ResumeHalf();sim.Advance(360);for(int side=0;side<2;side++){Assert.LessOrEqual(sim.State.completedPasses[side],sim.State.passes[side]);Assert.IsFalse(float.IsNaN(sim.State.metrics[side].AverageWidth));Assert.Greater(sim.State.metrics[side].possessionSeconds,50);}}
        [Test] public void PenaltyUsesSpotAndKeeperWaitsOnGoalLine(){var sim=Sim();var m=sim.State;m.restart=.1f;m.phase="penalty";m.restartSide=0;m.ball.owner=null;m.ball.position=new Point(41.5f,0);foreach(var p in m.actors)if(p.side==0&&p.slot>0)p.position=new Point(41.08f,0);m.actors[11].position=new Point(52.5f,0);for(int i=0;i<400&&m.phase=="penalty";i++)sim.Advance(.1);Assert.IsTrue(m.ball.penalty);Assert.That(m.ball.start.x,Is.EqualTo(41.5f).Within(.01));sim.Advance(.1);Assert.That(m.actors[11].position.x,Is.EqualTo(52.5f).Within(.02));Assert.Less(m.ball.elapsed,0);}
    }
}

