using System;using System.Linq;using NUnit.Framework;using Touchline.Core;
namespace Touchline.Tests{
 public sealed class TacticalFormationAssignmentTests{
 Database db;Career c;string[] original;
 [SetUp]public void Setup(){c=StaffTrainingLifecycleTests.Fixture(out db);c.lineup=Enumerable.Range(0,11).Select(i=>"p"+i).ToArray();for(int i=0;i<11;i++){var p=db.Find(c.lineup[i]);p.positions=new[]{c.tactic.withoutBall[i].role};p.position=i==0?"GB":"MIL";}original=c.lineup.ToArray();}
 MatchSimulation Live(){var sim=MatchSimulation.Create(db,c,"c1");c.match=sim.State;c.ApplyMatchContext(sim);sim.State.restart=0;sim.State.clock=100;return sim;}
 [Test]public void Forward433To4231KeepsStrikerAndBothFlanksInTheirRoles(){c.ChangeTacticalFormation(db,"4-2-3-1");Assert.AreEqual(original[9],c.lineup[10]);Assert.AreEqual(original[8],c.lineup[7]);Assert.AreEqual(original[10],c.lineup[9]);CollectionAssert.AreEquivalent(original,c.lineup);Assert.AreEqual(original[0],c.lineup[0]);}
 [Test]public void Inverse4231To433KeepsStrikerAndFlanks(){c.ChangeTacticalFormation(db,"4-2-3-1");c.ChangeTacticalFormation(db,"4-3-3");Assert.AreEqual(original[9],c.lineup[9]);Assert.AreEqual(original[8],c.lineup[8]);Assert.AreEqual(original[10],c.lineup[10]);}
 [TestCase("4-4-2")][TestCase("4-2-3-1")][TestCase("3-4-2-1")]
 public void ChangesConserveExactlyTheSameElevenAndTacticalInstructions(string shape){c.tactic.tempo=.87f;c.tactic.attackFocus="left";c.tactic.counterPress=true;c.ChangeTacticalFormation(db,shape);CollectionAssert.AreEquivalent(original,c.lineup);Assert.AreEqual(original[0],c.lineup[0]);Assert.AreEqual(.87f,c.tactic.tempo);Assert.AreEqual("left",c.tactic.attackFocus);Assert.IsTrue(c.tactic.counterPress);}
 [Test]public void SameFormationNeverUndoesManualPlacement(){c.AssignTacticalPlayer(db,8,original[10]);var manual=c.lineup.ToArray();c.tactic.withBall[8].x=44;c.ChangeTacticalFormation(db,"4-3-3");CollectionAssert.AreEqual(manual,c.lineup);Assert.AreEqual(44,c.tactic.withBall[8].x);}
 [Test]public void LiveFormationRetainsActorsBallFitnessCautionsAndPositions(){var sim=Live();var player=sim.State.actors[9];player.fitness=63;player.yellows=1;player.position=new Point(12,7);sim.State.ball.owner=player.id;var originalActors=sim.State.actors.ToArray();c.ChangeTacticalFormation(db,"4-2-3-1");Assert.AreSame(player,sim.State.actors[10]);Assert.AreEqual(63,player.fitness);Assert.AreEqual(1,player.yellows);Assert.AreEqual(12,player.position.x);Assert.AreEqual(7,player.position.z);Assert.AreEqual(player.id,sim.State.ball.owner);Assert.AreSame(c.tactic,sim.State.homeTactic);CollectionAssert.AreEquivalent(originalActors,sim.State.actors);for(int i=0;i<22;i++)Assert.AreEqual(i%11,sim.State.actors[i].slot);}
 [Test]public void PendingSubstitutionFollowsPlayerIdentityToNewSlot(){var sim=Live();var id=sim.State.actors[9].id;sim.RequestSubstitution(0,9,"p23");c.ChangeTacticalFormation(db,"4-2-3-1");Assert.AreEqual(id,sim.State.pendingSubstitutions.Single().outgoing);Assert.AreEqual(0,sim.State.substitutions[0]);sim.State.restart=1;sim.Advance(.1);Assert.AreEqual("p23",sim.State.actors[10].id);Assert.AreEqual(1,sim.State.substitutions[0]);Assert.AreEqual(id,c.lineup[10]);}
 [Test]public void ExcludedSlotStaysEmptyAndEmergencyGoalkeeperIsProtected(){var sim=Live();sim.SendOff(sim.State.actors[0].id);var emergency=sim.State.actors[0];int excluded=Array.FindIndex(sim.State.actors,a=>a.side==0&&a.sentOff);var red=sim.State.actors[excluded];c.ChangeTacticalFormation(db,"4-2-3-1");Assert.AreSame(emergency,sim.State.actors[0]);Assert.AreSame(red,sim.State.actors[excluded]);Assert.IsTrue(red.sentOff);Assert.AreEqual(10,sim.State.actors.Count(a=>a.side==0&&!a.sentOff));}
 [Test]public void InvalidFormationDoesNotMutateSelection(){Assert.Throws<ArgumentException>(()=>c.ChangeTacticalFormation(db,"1-1-8"));CollectionAssert.AreEqual(original,c.lineup);Assert.AreEqual("4-3-3",c.tactic.formation);}
 [Test]public void FinishedMatchDoesNotAllowReassignment(){var sim=Live();sim.State.finished=true;Assert.Throws<InvalidOperationException>(()=>c.ChangeTacticalFormation(db,"4-2-3-1"));CollectionAssert.AreEqual(original,c.lineup);}
 [Test]public void RepeatedRunsUseDeterministicAssignment(){c.ChangeTacticalFormation(db,"3-4-2-1");var expected=c.lineup.ToArray();Setup();c.ChangeTacticalFormation(db,"3-4-2-1");CollectionAssert.AreEqual(expected,c.lineup);}
 [Test]public void NativeSaveReloadAfterFormationPreservesPendingChangeAndSimulation(){var sim=Live();sim.RequestSubstitution(0,9,"p23");c.ChangeTacticalFormation(db,"4-2-3-1");var restored=UnityEngine.JsonUtility.FromJson<Career>(UnityEngine.JsonUtility.ToJson(c));restored.BindMatchTactic();Assert.AreSame(restored.tactic,restored.match.homeTactic);CollectionAssert.AreEqual(c.TacticalEleven,restored.TacticalEleven);Assert.AreEqual(c.match.pendingSubstitutions.Single().outgoing,restored.match.pendingSubstitutions.Single().outgoing);var replay=new MatchSimulation(db,restored.match);sim.State.restart=1;replay.State.restart=1;for(int i=0;i<100;i++){sim.Advance(.1);replay.Advance(.1);}Assert.AreEqual(UnityEngine.JsonUtility.ToJson(sim.State),UnityEngine.JsonUtility.ToJson(replay.State));}
 }}
