using System;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using Touchline.Core;
namespace Touchline.Tests
{
    public sealed class VerifiedStaffCatalogTests
    {
        Database db; Career c;
        void Setup(int day=0, string own="132")
        {
            db=new Database{clubs=new[]{new ClubData{id="132",name="Bayern Munich",playable=true,annualRevenue=861000000},new ClubData{id="382",name="Manchester City",playable=true,annualRevenue=829000000},new ClubData{id="83",name="Barcelona",playable=true,annualRevenue=975000000},new ClubData{id="2686",name="Barcelona SC",playable=true,annualRevenue=10500000}},players=new PlayerData[0],leagues=new LeagueData[0]};
            c=new Career{club=own,life=new ClubLife{day=day,revenue=861000000,cash=100000000}};
            c.EnsureStaffMarket(db);
        }
        StaffMember Real(string key)=>c.staffMarket.Single(s=>s.id=="real-"+key);
        [TestCase(0,3)][TestCase(22,3)][TestCase(23,8)][TestCase(111,8)][TestCase(112,13)][TestCase(113,0)][TestCase(3650,0)]
        public void FreshImportRespectsEvidenceWindow(int day,int expected){Setup(day);Assert.AreEqual(expected,c.staffMarket.Count(s=>!s.fictional));}
        [Test] public void AnnouncementAndObservationDatesDoNotPretendJuneKnowledge(){Setup();Assert.IsFalse(c.staffMarket.Any(s=>s.id=="real-roberto-vitiello"));c.life.day=23;c.EnsureStaffMarket(db);Assert.NotNull(Real("roberto-vitiello"));Assert.IsFalse(c.staffMarket.Any(s=>s.id=="real-marcus-sorg"));c.life.day=112;c.EnsureStaffMarket(db);Assert.NotNull(Real("marcus-sorg"));}
        [Test] public void PublishedBayernContractEndIsNotRelativeToLoadDay(){Setup(112);foreach(var s in c.staffMarket.Where(s=>!s.fictional&&s.club=="132"))Assert.AreEqual(new DateTime(2029,6,30),Career.Epoch.AddDays(s.until));}
        [Test] public void UnknownExpiryAndAllRatingsAndPayAreExplicitEstimates(){Setup(112);foreach(var s in c.staffMarket.Where(s=>!s.fictional)){StringAssert.Contains("Notes et salaire estimés",s.biography);Assert.Greater(s.wage,0);Assert.That(s.tactics,Is.InRange(1,20));if(s.club!="132"){StringAssert.Contains("durée simulée",s.biography);Assert.AreEqual(new DateTime(2028,10,4),Career.Epoch.AddDays(s.until));}}}
        [Test] public void ExistingCareerSelectionAndContractRemainUntouched(){Setup();var selected=c.Staff("assistant");selected.name="Coach engagé dans ma carrière";selected.wage=1234;selected.until=777;selected.tactics=19;c.life.day=112;var offers=c.staffOffers;c.EnsureStaffMarket(db);Assert.AreSame(selected,c.Staff("assistant"));Assert.AreEqual(1234,selected.wage);Assert.AreEqual(777,selected.until);Assert.AreEqual(19,selected.tactics);Assert.AreSame(offers,c.staffOffers);}
        [Test] public void RepeatedMigrationNeverDuplicatesOrResetsReleasedStaff(){Setup();var s=Real("aaron-danks");s.club=null;s.until=0;s.wage=4321;for(int i=0;i<5;i++)c.EnsureStaffMarket(db);Assert.AreEqual(1,c.staffMarket.Count(x=>x.id==s.id));Assert.IsNull(s.club);Assert.AreEqual(0,s.until);Assert.AreEqual(4321,s.wage);}
        [Test] public void TransferredRealIdentityStaysWithItsNewClub(){Setup();var s=Real("rene-maric");s.club="382";s.until=500;s.wage=9876;c.EnsureStaffMarket(db);Assert.AreEqual("382",s.club);Assert.AreEqual(500,s.until);Assert.AreEqual(9876,s.wage);Assert.IsFalse(c.life.staff.members.Any(x=>x.id==s.id));}
        [Test] public void LegacySameNameWithDifferentIdWinsOverCatalog(){Setup();c.staffMarket.RemoveAll(s=>s.id=="real-aaron-danks");var legacy=new StaffMember{id="legacy-person",name="AARON DANKS",club=null,role="assistant",until=55,wage=321};c.staffMarket.Add(legacy);c.EnsureStaffMarket(db);Assert.IsFalse(c.staffMarket.Any(s=>s.id=="real-aaron-danks"));Assert.IsNull(legacy.club);}
        [Test] public void ClubIdDoesNotConfuseBarcelonaWithEcuadorianClub(){Setup(112,"2686");Assert.IsFalse(c.staffMarket.Any(s=>!s.fictional&&s.club=="2686"));Assert.IsTrue(c.life.staff.members.All(s=>s.fictional));}
        [Test] public void UnsupportedClubIsNotInventedAndHeadCoachesAreExcluded(){Setup(112);Assert.IsFalse(c.staffMarket.Any(s=>new[]{"Hansi Flick","Enzo Maresca","Vincent Kompany","Michael Rechner","Michele De Bernardin"}.Contains(s.name)));Assert.IsTrue(c.staffMarket.Where(s=>!s.fictional).All(s=>s.role=="assistant"||s.role=="fitness"));Assert.AreEqual(0,c.staffMarket.Count(s=>!s.fictional&&s.club==null));}
        [Test] public void SourceAndRoleMappingAreVisible(){Setup(112);StringAssert.Contains("regroupé",Real("willy-caballero").biography);StringAssert.Contains("nomination non vérifiée",Real("marcus-sorg").biography);Assert.IsTrue(c.staffMarket.Where(s=>!s.fictional).All(s=>s.source.StartsWith("https://")));}
        [Test] public void SerializationKeepsReleasedIdentityAndDoesNotReplayTheSnapshot(){Setup(112);var s=Real("pepe-conde");s.club=null;s.until=0;var saved=JsonUtility.FromJson<Career>(JsonUtility.ToJson(c));saved.EnsureStaffMarket(db);var found=saved.staffMarket.Single(x=>x.id==s.id);Assert.IsNull(found.club);Assert.AreEqual(0,found.until);Assert.AreEqual(13,saved.staffMarket.Count(x=>!x.fictional));}
        [Test] public void LaterCareerRetainsImportedPeopleButDoesNotImportMissingSnapshot(){Setup(112);c.staffMarket.RemoveAll(s=>s.id=="real-aaron-danks");c.life.day=3650;c.EnsureStaffMarket(db);Assert.AreEqual(12,c.staffMarket.Count(s=>!s.fictional));Assert.IsFalse(c.staffMarket.Any(s=>s.id=="real-aaron-danks"));}
        [Test] public void CatalogImportDoesNotSpendMoneyOrCreateOffer(){Setup();long cash=c.life.cash;c.life.day=112;c.EnsureStaffMarket(db);Assert.AreEqual(cash,c.life.cash);Assert.AreEqual(0,c.staffOffers.Count);}
        [Test] public void RealEmploymentUsesExistingNegotiationAndReleaseRules(){Setup(112);c.life.reputation=90;var incoming=Real("roberto-vitiello");var outgoing=c.Staff("assistant");long fee=c.StaffReleaseCost(incoming);Assert.Greater(fee,0);Assert.AreEqual(fee,c.StaffAgent(incoming.id).feeLow);c.FireStaff(db,outgoing.id);Assert.IsNull(outgoing.club);c.ProposeStaffContract(db,incoming.id,Career.MonthlySalary(incoming.wage*2),2);c.life.day+=2;typeof(Career).GetMethod("StaffMarketDay",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(c,new object[]{db});Assert.AreEqual("accepted",c.staffOffers.Single().status);c.SignStaffContract(db,incoming.id);Assert.AreEqual("132",incoming.club);Assert.AreEqual(c.life.day+730,incoming.until);Assert.AreSame(incoming,c.Staff("assistant"));c.EnsureStaffMarket(db);Assert.IsNull(outgoing.club);Assert.AreEqual("132",incoming.club);Assert.AreEqual("signed",c.staffOffers.Single().status);}
        [Test] public void MissingAndNonPlayableClubsReceiveNoImportedStaff(){Setup();c.staffMarket.RemoveAll(s=>!s.fictional);db.clubs=db.clubs.Where(t=>t.id!="132").ToArray();db.clubs.Single(t=>t.id=="83").playable=false;c.life.day=112;c.EnsureStaffMarket(db);Assert.AreEqual(5,c.staffMarket.Count(s=>!s.fictional));Assert.IsTrue(c.staffMarket.Where(s=>!s.fictional).All(s=>s.club=="382"));}
        [TestCase(22,8)][TestCase(111,13)] public void AdvanceDayVisitsTheEvidenceDate(int before,int expected){Setup(before);c.life.nextFixture=int.MaxValue;c.AdvanceDay(db);Assert.AreEqual(before+1,c.life.day);Assert.AreEqual(expected,c.staffMarket.Count(s=>!s.fictional));}
        [Test] public void HumanWeeklyPayrollOnlyChargesTheFourSelectedJobs(){Setup(112);c.world=new CareerWorld();long selected=c.life.staff.members.Sum(s=>s.wage);Assert.AreEqual(4,c.life.staff.members.Count);Assert.AreEqual(4,c.life.staff.members.Select(s=>s.role).Distinct().Count());typeof(Career).GetMethod("StaffDay",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(c,new object[]{db});Assert.AreEqual(-selected,c.life.ledger.Single(e=>e.label=="Salaires du staff").amount);}
        [Test] public void AllImportedContractsFitTheExistingAiWeeklyEnvelope(){Setup(112);foreach(var team in db.clubs){long payroll=c.staffMarket.Where(s=>s.club==team.id).Sum(s=>s.wage);Assert.LessOrEqual(payroll,Math.Max(1500,team.annualRevenue/52/40),team.name);}Assert.AreEqual(13,c.staffMarket.Count(s=>!s.fictional));}
    }
}
