namespace Touchline.Core
{
    // Presentation-only trace of an outfield shot block in the last step.
    // It is regenerated by physics and does not belong in career saves.
    public struct BallImpactContact
    {
        public bool valid;public float clock,fraction,startHeight,height;
        public Point start,impact;
    }
    public sealed partial class MatchSimulation
    {
        public BallImpactContact ImpactContact {get;private set;}
        void RecordBallImpact(float fraction,Point impact,float height)
        {
            ImpactContact=new BallImpactContact{valid=true,clock=State.clock,fraction=Mathx.Clamp(fraction,0,1),start=State.ball.previous,startHeight=State.ball.previousHeight,impact=impact,height=height};
        }
    }
}
